### ISSUE TITLE
 panic: unexpected keypair dbname='XXXX' from pq

### ISSUE THREAD

**Issue by saputradharma** [grafana/agent#1110]
Can't start freshly installed grafana agent. Got this error while starting the service:

```
panic: unexpected keypair dbname='xxxx' from pq
Nov 18 22:11:48 ip-10-0-x-xx grafana-agent[13306]: goroutine 1 [running]:
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations/postgres_exporter.parsePostgresURL(0xc00070c140, 0x4d, 0x1, 0x1, 0x0)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/postgres_exporter/postgres_exporter.go:90 +0x2eb
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations/postgres_exporter.(*Config).InstanceKey(0xc000125520, 0xc000945d88, 0x13, 0x2, 0x2, 0xc000945d88, 0x13)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/postgres_exporter/postgres_exporter.go:58 +0x85
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations.(*Manager).ApplyConfig(0xc000950ea0, 0x1, 0xc000dd2fb0, 0x1, 0x1, 0x0, 0xc0005a00a8, 0x1, 0x1, 0x12a05f200, ...)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/manager.go:252 +0x1939
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: github.com/grafana/agent/pkg/integrations.NewManager(0x1, 0xc000dd2fb0, 0x1, 0x1, 0x0, 0xc0005a00a8, 0x1, 0x1, 0x12a05f200, 0x3039, ...)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/pkg/integrations/manager.go:182 +0x1f8
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: main.NewEntrypoint(0xc000d73890, 0xc00096a000, 0xc000dd2b10, 0xc000dd3cf0, 0x4419e5, 0xc000076710)
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/cmd/agent/entrypoint.go:93 +0x54a
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]: main.main()
Nov 18 22:11:48 ip-10-0-x-xxx grafana-agent[13306]:         /drone/src/cmd/agent/main.go:66 +0x1d
```

Sample configuration `/etc/grafana-agent.yml`:

```
integrations:
  postgres_exporter:
    data_source_names:
    - "postgresql://linus:42secret@localhost:5432/postgres?sslmode=disable"
    enabled: true
    
    ......
```

Seems there are bugs with the `postgres_exporter.parsePostgresURL()`

tried to reproduce in this golang playground got the same result: https://play.golang.org/p/oEukXPOHXvc

**Comment by rfratto** [comment]
Hi, thanks for reporting. We have a fix, but there's a workaround you can use in the meantime by manually setting the `instance` value for the integration:

```yaml
integrations:
  postgres_exporter:
    data_source_names:
    - "postgresql://linus:42secret@localhost:5432/postgres?sslmode=disable"
    enabled: true
```

**Comment by saputradharma** [comment]
Cool. The temporary workaround works well.
