### ISSUE TITLE
Panic when reloading a changed server config block

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1156]
Grafana Agent panics when invoking `/-/reload` after the server block has changed:

Run agent:
```
go run ./cmd/agent --config.file ./cmd/agent/agent-local-config.yaml --metrics.wal-directory=/tmp/agent
```

Change config file, then reload:

```
curl localhost:12345/-/reload
```

Panic along with the panic:

```
2021-12-08 16:32:25.502488 I | http: panic serving [::1]:49904: duplicate metrics collector registration attempted
goroutine 156 [running]:
net/http.(*conn).serve.func1(0x140005c0820)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:1801 +0xdc
panic({0x10397cd60, 0x1400158bb40})
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/panic.go:1052 +0x2ac
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0x14000d13de8, {0x103f66ce0, 0x105cee900})
	/Users/robert/dev/go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:150 +0x160
panic({0x10397cd60, 0x1400158bb40})
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/panic.go:1038 +0x21c
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x14000062a50, {0x140007d8d90, 0x1, 0x1})
	/Users/robert/dev/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:403 +0xac
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/Users/robert/dev/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:178
github.com/weaveworks/common/server.New({{0x102a79b81, 0x5}, {0x102a77b20, 0x3}, {0x0, 0x0}, 0x3039, 0x0, {0x102a77b20, 0x3}, ...})
	/Users/robert/dev/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20211104141906-05b06253aab8/server/server.go:178 +0x1c4
github.com/grafana/agent/pkg/util/server.(*Server).ApplyConfig(0x14000c7dc00, {{0x102a79b81, 0x5}, {0x102a77b20, 0x3}, {0x0, 0x0}, 0x3039, 0x0, {0x102a77b20, ...}, ...}, ...)
	/Users/robert/dev/grafana/agent/pkg/util/server/server.go:94 +0x3a4
main.(*Entrypoint).ApplyConfig(0x14000e23500, {{{0x102a79b81, 0x5}, {0x102a77b20, 0x3}, {0x0, 0x0}, 0x3039, 0x0, {0x102a77b20, ...}, ...}, ...})
	/Users/robert/dev/grafana/agent/cmd/agent/entrypoint.go:118 +0x2dc
main.(*Entrypoint).TriggerReload(0x14000e23500)
	/Users/robert/dev/grafana/agent/cmd/agent/entrypoint.go:213 +0x2fc
main.(*Entrypoint).reloadHandler(0x14000e23500, {0x103ecbb40, 0x14000afb080}, 0x1400014ab00)
	/Users/robert/dev/grafana/agent/cmd/agent/entrypoint.go:192 +0x28
net/http.HandlerFunc.ServeHTTP(0x14000f76940, {0x103ecbb40, 0x14000afb080}, 0x1400014ab00)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0x140005d0900, {0x103ecbb40, 0x14000afb080}, 0x1400014a900)
	/Users/robert/dev/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1e4
github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2({0x103ecbb40, 0x14000afb080})
	/Users/robert/dev/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20211104141906-05b06253aab8/middleware/instrument.go:70 +0x48
github.com/felixge/httpsnoop.CaptureMetricsFn({0x103ebdb60, 0x140006513b0}, 0x14000d796b8)
	/Users/robert/dev/go/pkg/mod/github.com/felixge/httpsnoop@v1.0.2/capture_metrics.go:76 +0x1f0
github.com/weaveworks/common/middleware.Instrument.Wrap.func1({0x103ebdb60, 0x140006513b0}, 0x1400014a900)
	/Users/robert/dev/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20211104141906-05b06253aab8/middleware/instrument.go:69 +0x298
net/http.HandlerFunc.ServeHTTP(0x140000625a0, {0x103ebdb60, 0x140006513b0}, 0x1400014a900)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x40
github.com/weaveworks/common/middleware.Log.Wrap.func1({0x103ecbf60, 0x14000651310}, 0x1400014a900)
	/Users/robert/dev/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20211104141906-05b06253aab8/middleware/logging.go:53 +0x258
net/http.HandlerFunc.ServeHTTP(0x14000e03cc0, {0x103ecbf60, 0x14000651310}, 0x1400014a900)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x40
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5({0x103eca1c0, 0x14000afc0e0}, 0x1400014a800)
	/Users/robert/dev/go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:154 +0x654
net/http.HandlerFunc.ServeHTTP(0x14000e03d00, {0x103eca1c0, 0x14000afc0e0}, 0x1400014a800)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:2046 +0x40
net/http.serverHandler.ServeHTTP({0x14000e0e460}, {0x103eca1c0, 0x14000afc0e0}, 0x1400014a800)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:2878 +0x444
net/http.(*conn).serve(0x140005c0820, {0x103ef3390, 0x1400122bd10})
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:1929 +0xb6c
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/net/http/server.go:3033 +0x4b8
```

It looks like our current dependency on github.com/weaveworks/common/server (which is a temporary fork at the moment IIRC) registers metrics to the global registrar instead of the one we configure.

**Comment by rfratto** [comment]
This would be superseded by #1136.
