### ISSUE TITLE
Panic during shutdown

### ISSUE THREAD

**Issue by amckinley** [grafana/agent#179]
After killing the agent with a ctrl-c:

```
level=info ts=2020-09-02T23:29:54.237414373Z caller=wal.go:423 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="WAL checkpoint complete" first=189 last=195 duration=41.297111278s
^Clevel=info ts=2020-09-02T23:34:54.52948527Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2020-09-02T23:34:54.52987509Z caller=instance.go:297 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="stopping truncation loop..."
level=info ts=2020-09-02T23:34:54.529886854Z caller=instance.go:319 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="stopping scrape manager..."
level=info ts=2020-09-02T23:34:54.530004594Z caller=instance.go:526 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="discovery manager stopped"
level=info ts=2020-09-02T23:34:54.530108567Z caller=instance.go:529 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="stopping discovery manager..."
level=info ts=2020-09-02T23:34:54.872412398Z caller=instance.go:332 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="closing storage..."
level=info ts=2020-09-02T23:34:54.872577813Z caller=instance.go:313 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="scrape manager stopped"
ts=2020-09-02T23:34:54.872700988Z caller=dedupe.go:112 agent=prometheus instance=5df40780494f25472649ea5095966285 component=remote level=info remote_name=cortex url=http://localhost:1234/receive msg="Stopping remote storage..."
ts=2020-09-02T23:34:54.90359832Z caller=dedupe.go:112 agent=prometheus instance=5df40780494f25472649ea5095966285 component=remote level=info remote_name=cortex url=http://localhost:1234/receive msg="WAL watcher stopped" queue=cortex
ts=2020-09-02T23:34:54.903633143Z caller=dedupe.go:112 agent=prometheus instance=5df40780494f25472649ea5095966285 component=remote level=info remote_name=cortex url=http://localhost:1234/receive msg="Stoping metadata watcher..."
ts=2020-09-02T23:34:54.903674878Z caller=dedupe.go:112 agent=prometheus instance=5df40780494f25472649ea5095966285 component=remote level=info remote_name=cortex url=http://localhost:1234/receive msg="Scraped metadata watcher stopped"
level=info ts=2020-09-02T23:34:55.870339333Z caller=wal.go:358 agent=prometheus instance=5df40780494f25472649ea5095966285 msg="series GC completed" duration=1.358675992s
panic: send on closed channel

goroutine 750 [running]:
github.com/prometheus/prometheus/tsdb/wal.(*WAL).nextSegment(0xc000392870, 0x33, 0xc2ee8bd800)
        /home/runner/work/agent/agent/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:481 +0xf6
github.com/prometheus/prometheus/tsdb/wal.(*WAL).NextSegment(0xc000392870, 0x0, 0x0)
        /home/runner/work/agent/agent/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:460 +0x78
github.com/grafana/agent/pkg/prom/wal.(*Storage).Truncate(0xc000c784e0, 0x174512c5530, 0x4, 0x4)
        /home/runner/work/agent/agent/pkg/prom/wal/wal.go:367 +0x24f
github.com/grafana/agent/pkg/prom/instance.(*Instance).truncateLoop(0xc0003b0c60, 0x2caf5c0, 0xc0a3a34ac0, 0x2ccffe0, 0xc000c784e0, 0xc00078e060)
        /home/runner/work/agent/agent/pkg/prom/instance/instance.go:581 +0x3b8
github.com/grafana/agent/pkg/prom/instance.(*Instance).Run.func1(0x0, 0x0)
        /home/runner/work/agent/agent/pkg/prom/instance/instance.go:292 +0x60
github.com/oklog/run.(*Group).Run.func1(0xc0a3ac8600, 0xc0a3ddb500, 0xc0a37b9d40)
        /home/runner/work/agent/agent/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
        /home/runner/work/agent/agent/vendor/github.com/oklog/run/group.go:37 +0xbb
```

```
$ uname -a
Linux ip-10-1-5-195 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ./agent-linux-amd64 --version
agent, version v0.5.0 (branch: HEAD, revision: 86f7b71)
  build user:       runner@fv-az151
  build date:       2020-08-12T14:40:24Z
  go version:       go1.14.4
```

**Comment by rfratto** [comment]
Thanks for reporting this! It looks like the WAL storage is able to be closed in the middle of a truncation. I'll have a PR to fix this tomorrow.
