### ISSUE TITLE
Flow: metrics.scrape panics after first scrape

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1945]
Use the following config file with the current Flow implementation in main:

```hcl
logging {
  level  = "debug"
  format = "logfmt"
}

metrics "scrape" "default" {
  targets = [{
    "__address__" = "demo.robustperception.io:9090",
  }]
  forward_to = [metrics.remote_write.default.receiver]

  scrape_config {
    job_name = "default"
  }
}

metrics "remote_write" "default" {
  remote_write {
    url = "http://localhost:9009/api/prom/push"
  }
}
```

After the first scrape, the component will panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10462a528]

goroutine 115 [running]:
github.com/grafana/agent/component/common/appendable.(*flowAppender).Commit(0x14000bce6e0)
	/Users/robert/dev/grafana/agent/component/common/appendable/appendable.go:74 +0xf8
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1()
	/Users/robert/dev/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20220413182558-6b32d0b957c5/scrape/scrape.go:1263 +0x48
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0x14000b84680, {0xeda6f5fa8?, 0x1053a51e0?, 0x0?}, {0xeda6f5fa8?, 0x1053a51e0?, 0x1053a51e0?}, 0x0)
	/Users/robert/dev/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20220413182558-6b32d0b957c5/scrape/scrape.go:1334 +0xb5c
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0x14000b84680, 0x14000290240?)
	/Users/robert/dev/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20220413182558-6b32d0b957c5/scrape/scrape.go:1216 +0x284
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/Users/robert/dev/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20220413182558-6b32d0b957c5/scrape/scrape.go:587 +0x880
exit status 2
```

The issue seems to be that the appendable is created [once](https://github.com/grafana/agent/blob/1fda90adc917c8d107e2e2a0207611adc43222b4/component/metrics/scrape/scrape.go#L71-L74), and the appendable the scraper uses never updates after construction.

`metrics.remote_write` initially exports a nil receiver, which is where `metrics.scrape` is getting it from. This also shouldn't be happening, but is a separate issue (#1946).

`metrics.scrape` needs to:

1. Protect against trying to invoke nil receivers 
2. Allow the receivers list to change as the component gets updated

**Comment by rfratto** [comment]
cc @tpaschalis

**Comment by tpaschalis** [comment]
Thanks for the heads up. I broke something on https://github.com/grafana/agent/commit/7be5f6c04c3d8b814c1c74de40d46bb7ce7c1f37 when moving some internal structs so they could be reused; I'll get to fixing this
