### ISSUE TITLE
flow: panic when failing to build unlabelled component

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2095]
The following configuration panics about 50% of the time. It likely has to do with the unlabelled local.file component, as adding a label to it makes it so that it never panics. 

```river
logging {
	level  = "debug"
	format = "logfmt"
}

local.file "this_file" {
	filename = "./cmd/agent/test-local-file.txt"
	detector = "fsnotify"
}

local.file {
	foo = "bar"
}

prometheus.scrape "default" {
	targets = [{
		"__address__"   = "localhost:12345",
		"dynamic_label" = local.file.this_file.content,
	}]
	forward_to = [prometheus.remote_write.default.receiver]

	scrape_config {
		job_name = "default"
	}
}

prometheus.remote_write "default" {
	remote_write {
		url = "http://localhost:9009/api/prom/push"
	}
}
```

The produced panic
```
$ EXPERIMENTAL_ENABLE_FLOW=true ./cmd/agent/agent run ./cmd/agent/example-config.river
ts=2022-08-31T08:39:07.098555Z level=error msg="failed to evaluate component" component=local.file err="decoding River: missing required attribute \"filename\""
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/grafana/agent/pkg/flow/internal/controller.(*valueCache).buildValue(0x14000d9a390, {0x14000d9b260, 0x2, 0x4?}, 0x2)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/value_cache.go:133 +0x310
github.com/grafana/agent/pkg/flow/internal/controller.(*valueCache).buildValue(0x14000d9a390, {0x14000d9b200, 0x2, 0x5?}, 0x1)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/value_cache.go:139 +0x17c
github.com/grafana/agent/pkg/flow/internal/controller.(*valueCache).BuildContext(0x14000d9a390, 0x0)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/value_cache.go:105 +0x2cc
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).evaluate(0x14000dd8630, 0x0?, 0x14000da0540)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/loader.go:270 +0x30
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply.func1({0x105c9d788?, 0x14000da0540})
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/loader.go:106 +0x1e8
github.com/grafana/agent/pkg/flow/internal/dag.WalkTopological(0x14000a5b1c0, {0x14000ec56c0, 0x3, 0x4?}, 0x14000ebf648)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/dag/walk.go:110 +0x180
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x14000dd8630, 0x0, {0x14000a5b120, 0x4, 0x4})
	/Users/tpaschalis/GitRepos/agent/pkg/flow/internal/controller/loader.go:100 +0x59c
github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x14000ecab00, 0x140004ba370)
	/Users/tpaschalis/GitRepos/agent/pkg/flow/flow.go:196 +0x128
main.(*flowRun).Run.func1()
	/Users/tpaschalis/GitRepos/agent/cmd/agent/flow_run.go:112 +0xbc
main.(*flowRun).Run(0x14000d9a030, {0x16f4b77de, 0x20})
	/Users/tpaschalis/GitRepos/agent/cmd/agent/flow_run.go:118 +0x204
main.runCommand.func1(0x14000bc9180?, {0x1400019b120?, 0x1?, 0x1?})
	/Users/tpaschalis/GitRepos/agent/cmd/agent/flow_run.go:69 +0x3c
github.com/spf13/cobra.(*Command).execute(0x14000bc9180, {0x1400019b060, 0x1, 0x1})
	/Users/tpaschalis/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000bc8f00)
	/Users/tpaschalis/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tpaschalis/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.runFlow()
	/Users/tpaschalis/GitRepos/agent/cmd/agent/flow.go:32 +0xe8
main.main()
	/Users/tpaschalis/GitRepos/agent/cmd/agent/main.go:45 +0x64
```

While when the other 50% of the time, the Agent tries to start up successfully and reports the error only after some of the other components are initialized.
```
$ EXPERIMENTAL_ENABLE_FLOW=true ./cmd/agent/agent run ./cmd/agent/example-config.river
ts=2022-08-31T08:39:23.779673Z level=info component=prometheus.remote_write.default subcomponent=wal msg="replaying WAL, this may take a while" dir=data-agent/prometheus.remote_write.default/wal/prometheus.remote_write.default/wal
ts=2022-08-31T08:39:23.785999Z level=info component=prometheus.remote_write.default subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=49
...
...
ts=2022-08-31T08:39:23.789493Z level=info component=prometheus.remote_write.default subcomponent=wal msg="WAL segment loaded" segment=49 maxSegment=49
ts=2022-08-31T08:39:23.79582Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=618d80 url=http://localhost:9009/api/prom/push msg="Starting WAL watcher" queue=618d80
ts=2022-08-31T08:39:23.795848Z level=error msg="failed to evaluate component" component=local.file err="decoding River: missing required attribute \"filename\""
ts=2022-08-31T08:39:23.795878Z level=error msg="failed to evaluate component" component=prometheus.scrape.default err="decoding River: ./cmd/agent/example-config.river:20:32: field \"this_file\" does not exist"
Error: ./cmd/agent/example-config.river:13:1: Failed to build component: decoding River: missing required attribute "filename"

12 |
13 | | local.file {
   |  _^^^^^^^^^^^^
14 | |     foo = "bar"
15 | | }
   | |_^
16 |

Error: ./cmd/agent/example-config.river:20:32: field "this_file" does not exist

19 |         "__address__"   = "demo.robustperception.io:9090",
20 |         "dynamic_label" = local.file.this_file.content,
   |                                      ^^^^^^^^^
21 |     }]

Error: could not perform the initial load successfully
```

**Comment by tpaschalis** [comment]
The issue was fixed with #2164 as the component without a label is rejected earlier on. Closing this.
