### ISSUE TITLE
panic on spanmetricsprocessor with grafana agent v0.26.1

### ISSUE THREAD

**Issue by vbichov** [grafana/agent#2255]
running grafana-agent in kubernetes encountered the following:

using docker image `FROM grafana/agent:v0.26.1`

```
panic: runtime error: index out of range [17] with length 17

goroutine 408 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).updateLatencyMetrics(...)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.46.0/processor.go:439
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetricsForSpan(0xc0001fa000, {0xc0032180f0, 0x2b}, {0x0?}, {0x0?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.46.0/processor.go:392 +0x466
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetricsForServiceSpans(0x413ea5?, {0xc000e764e0?}, {0xc0032180f0, 0x2b})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.46.0/processor.go:376 +0x7d
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetrics(0xc003f93328?, {0x414207?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.46.0/processor.go:365 +0xd1
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces(0xc0001fa000, {0x52dc898, 0xc000e764e0}, {0x4?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.46.0/processor.go:230 +0x34
go.opentelemetry.io/collector/processor/processorhelper.NewTracesProcessor.func1({0x52dc898, 0xc000e764e0}, {0x0?})
	/go/pkg/mod/github.com/grafana/opentelemetry-collector@v0.4.1-0.20220315084747-b05fe1477960/processor/processorhelper/traces.go:71 +0x1dd
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeTracesFunc.ConsumeTraces(...)
	/go/pkg/mod/github.com/grafana/opentelemetry-collector@v0.4.1-0.20220315084747-b05fe1477960/consumer/consumerhelper/traces.go:29
go.opentelemetry.io/collector/receiver/otlpreceiver/external/trace.(*Receiver).Export(0xc000c2c120, {0x52dc898, 0xc00003a030}, {0xc00154cc00?})
	/go/pkg/mod/github.com/grafana/opentelemetry-collector@v0.4.1-0.20220315084747-b05fe1477960/receiver/otlpreceiver/external/trace/otlp.go:60 +0x113
go.opentelemetry.io/collector/model/otlpgrpc.rawTracesServer.Export(...)
	/go/pkg/mod/go.opentelemetry.io/collector/model@v0.46.0/otlpgrpc/traces.go:166
go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler.func1({0x52dc898, 0xc00003a030}, {0x46030c0?, 0xc001255860})
	/go/pkg/mod/go.opentelemetry.io/collector/model@v0.46.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:217 +0x78
go.opentelemetry.io/collector/config/configgrpc.enhanceWithClientInformation.func1({0x52dc898?, 0xc00154cbd0?}, {0x46030c0, 0xc001255860}, 0x0?, 0xc001255878)
	/go/pkg/mod/github.com/grafana/opentelemetry-collector@v0.4.1-0.20220315084747-b05fe1477960/config/configgrpc/configgrpc.go:382 +0x4c
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x52dc898?, 0xc00154cbd0?}, {0x46030c0?, 0xc001255860?})
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1116 +0x5b
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x52dc898, 0xc0009b9ef0}, {0x46030c0, 0xc001255860}, 0xc003331c80, 0xc00335cc80)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.29.0/interceptor.go:325 +0x664
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x52dc898?, 0xc0009b9ef0?}, {0x46030c0?, 0xc001255860?})
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1119 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1({0x52dc898, 0xc0009b9ef0}, {0x46030c0, 0xc001255860}, 0xc003331c80, 0xc001255878)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1121 +0x12b
go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler({0x3e84780?, 0xc000c10250}, {0x52dc898, 0xc0009b9ef0}, 0xc000f7b680, 0xc000c16420)
	/go/pkg/mod/go.opentelemetry.io/collector/model@v0.46.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:219 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000c4c000, {0x52f1420, 0xc0012869c0}, 0xc003216120, 0xc000c14b40, 0x76992e0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000c4c000, {0x52f1420, 0xc0012869c0}, 0xc003216120, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:919 +0x28a
```

**Comment by tpaschalis** [comment]
Hey Vitaly, thanks for the report! Could you share the configuration file that you're using after redacting any sensitive information?

**Comment by rfratto** [comment]
Hey Vitaly, we recently updated our OpenTelemetry Collector dependency to v0.61.0, so this issue might not be present anymore. Would you mind testing `grafana/agent:main-a2ee071` to see if the issue persists in that image?

**Comment by rfratto** [comment]
I'm going to close this as completed; we believe this won't happen in the v0.29 release scheduled for next week due to upgrading the OpenTelemetry Collector dependency. 

If this issue still appears in v0.29, please open a new issue so we can track it; comments on closed issues are likely to be missed.
