### ISSUE TITLE
Grafana-agent Errors

### ISSUE THREAD

**Issue by nick-wvu** [grafana/agent#2337]
I'm seeing the following errors
```
C:\Program Files\Grafana Agent>.\agent-windows-amd64.exe -config.file=.\agent-config.yaml
panic: ReqQueryValueEx failed: The system cannot find the file specified. errno 2

goroutine 1 [running]:
github.com/leoluk/perflib_exporter/perflib.QueryNameTable(0x459e310, 0xb, 0xc0000c39e0)
        /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/nametable.go:43 +0x330
github.com/leoluk/perflib_exporter/perflib.init.0()
        /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/perflib.go:266 +0x45
```

<img width="923" alt="image" src="https://user-images.githubusercontent.com/115032483/194879237-33517e34-fad7-402f-a678-957b17c687d2.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/115032483/194878360-13499840-bc25-4de4-bf97-6ce98898e429.png">

**Comment by smith84** [comment]
`TypePerf -q` gave me an error saying that it was unable to connect to the local system.
I attempted to load the Performance Counters in mmc.exe and was greeted with an error message starting with "Unable to add these counters"
A quick web search turned up this post https://www.jonathanneilly.co.uk/2021/01/05/perfmon-unable-to-add-these-counters/
Running `lodctr /r` has resolved the Performance Counters issue locally, and the Grafana Agent service now starts as expected.
