### ISSUE TITLE
windows_exporter MSSQL collector panic

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/agent#3122]
Server 2012 R2
SQL 14.0.2047.8
Grafana Agent v0.32.0-rc.0

The previous version of the agent crashes 

```
C:\Program Files\Grafana Agent>grafana-agent-windows-amd64.exe --config.file=".\
agent-config.yaml"
ts=2023-02-28T14:56:48.1694684Z caller=server.go:191 level=info msg="server list
ening on addresses" http=127.0.0.1:12345 grpc=127.0.0.1:12346 http_tls_enabled=f
alse grpc_tls_enabled=false
ts=2023-02-28T14:56:48.1704724Z caller=node.go:85 level=info agent=prometheus co
mponent=cluster msg="applying config"
ts=2023-02-28T14:56:48.1704724Z caller=remote.go:180 level=info agent=prometheus
 component=cluster msg="not watching the KV, none set"
ts=2023-02-28T14:56:48.1734704Z caller=promtail.go:123 level=info component=logs
 logs_config=integrations msg="Reloading configuration file" md5sum=3dd44bd0a942
35b0a5ed4bc7b9642a50
ts=2023-02-28T14:56:48.1844711Z caller=zapadapter.go:78 level=info component=tra
ces msg="Traces Logger Initialized"
ts=2023-02-28T14:56:48.1854706Z caller=wal.go:199 level=info agent=prometheus in
stance=7150d20b1bd90d41eac7c072f3a8c377 msg="replaying WAL, this may take a whil
e" dir=\tmp\grafana-agent-wal\7150d20b1bd90d41eac7c072f3a8c377\wal
time="2023-02-28T09:56:48-05:00" level=warning msg="No where-clause specified fo
r service collector. This will generate a very large number of metrics!" source=
"service.go:49"
ts=2023-02-28T14:56:48.1884704Z caller=wal.go:246 level=info agent=prometheus in
stance=7150d20b1bd90d41eac7c072f3a8c377 msg="WAL segment loaded" segment=0 maxSe
gment=4
ts=2023-02-28T14:56:48.1884704Z caller=windows_exporter_windows.go:32 level=info
 integration=windows_exporter msg="enabled windows_exporter collectors" collecto
rs=cpu,cs,logical_disk,logon,mssql,net,os,service,system,textfile
ts=2023-02-28T14:56:48.1924751Z caller=wal.go:246 level=info agent=prometheus in
stance=7150d20b1bd90d41eac7c072f3a8c377 msg="WAL segment loaded" segment=1 maxSe
gment=4
ts=2023-02-28T14:56:48.1944687Z caller=wal.go:246 level=info agent=prometheus in
stance=7150d20b1bd90d41eac7c072f3a8c377 msg="WAL segment loaded" segment=2 maxSe
gment=4
ts=2023-02-28T14:56:48.196474Z caller=wal.go:246 level=info agent=prometheus ins
tance=7150d20b1bd90d41eac7c072f3a8c377 msg="WAL segment loaded" segment=3 maxSeg
ment=4
ts=2023-02-28T14:56:48.1984734Z caller=wal.go:246 level=info agent=prometheus in
stance=7150d20b1bd90d41eac7c072f3a8c377 msg="WAL segment loaded" segment=4 maxSe
gment=4
ts=2023-02-28T14:56:48.2004693Z caller=dedupe.go:112 agent=prometheus instance=7
150d20b1bd90d41eac7c072f3a8c377 component=remote level=info remote_name=7150d2-5
d4ef0 url=http://mimir/api/v1/push msg="Starting WAL watcher" q
ueue=7150d2-5d4ef0
ts=2023-02-28T14:56:48.2014754Z caller=dedupe.go:112 agent=prometheus instance=7
150d20b1bd90d41eac7c072f3a8c377 component=remote level=info remote_name=7150d2-5
d4ef0 url=http://mimir/api/v1/push msg="Starting scraped metada
ta watcher"
ts=2023-02-28T14:56:48.2014754Z caller=dedupe.go:112 agent=prometheus instance=7
150d20b1bd90d41eac7c072f3a8c377 component=remote level=info remote_name=7150d2-5
d4ef0 url=http://mimir/api/v1/push msg="Replaying WAL" queue=71
50d2-5d4ef0
ts=2023-02-28T14:56:48.2154764Z caller=manager.go:198 level=info agent=prometheu
s msg="dynamically updated instance" instance=7150d20b1bd90d41eac7c072f3a8c377
ts=2023-02-28T14:56:48.2334726Z caller=manager.go:198 level=info agent=prometheu
s msg="dynamically updated instance" instance=7150d20b1bd90d41eac7c072f3a8c377
ts=2023-02-28T14:56:48.238471Z caller=reporter.go:103 level=info msg="running us
age stats reporter"
ts=2023-02-28T14:56:57.8998469Z caller=dedupe.go:112 agent=prometheus instance=7
150d20b1bd90d41eac7c072f3a8c377 component=remote level=info remote_name=7150d2-5
d4ef0 url=http://mimir/api/v1/push msg="Done replaying WAL" dur
ation=9.6985571s
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x58f603f]

goroutine 525 [running]:
github.com/prometheus-community/windows_exporter/collector.(*MSSQLCollector).exe
cute(0xc0006aa800, 0x0?, {0xc001baa1d5, 0x9}, 0x0, 0x0?, {0xc000476bd0, 0xb}, 0x
0?)
        /go/pkg/mod/github.com/grafana/windows_exporter@v0.15.1-0.20220202211901
-871715ba0b43/collector/mssql.go:1829 +0xdf
created by github.com/prometheus-community/windows_exporter/collector.(*MSSQLCol
lector).Collect
        /go/pkg/mod/github.com/grafana/windows_exporter@v0.15.1-0.20220202211901
-871715ba0b43/collector/mssql.go:1869 +0x193
```

```
integrations:
  agent:
    enabled: true
  labels:
    environment: production
  prometheus_remote_write:
  - url: http://mimir/api/v1/push
  windows_exporter:
    enabled: true
    enabled_collectors: "cpu,cs,logical_disk,logon,net,os,service,system,textfile,mssql"
    mssql:
      enabled_classes: "accessmethods,bufman,databases,genstats,locks,memmgr,sqlstats,sqlerrors,transactions,waitstats"
```

**Comment by marctc** [comment]
I'd assume that the problem come from upsteam. Did you try to run a newer version of windows_exporter and see if that happens? Alternatively you could use the mssql integration that we are about to release today.

**Comment by MaxDiOrio** [comment]
I have not tried a newer version of windows_exporter.  Browsing their open or closed issues doesn't show anything directly related.

I'll look into the new integration but it doesn't seem to export as many metrics by default vs the windows_exporter mssql integration.  Plus I've never been a fan of adding additional users into SQL and then having the login info in a text file on the server, even if the user is limited.

**Comment by MaxDiOrio** [comment]
There's the issue - waitstats wasn't released until after v0.17.0. Grafana Agent uses a 2 year old release, 0.16.0.

**Comment by marctc** [comment]
related to #3090
