### ISSUE TITLE
Having logging configuration on a sub-component results into a gopanic

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#3632]
Hi,

I found this by accident. If there is a submodule which contains a logging configuration, the agent will raise a go panic

module.river
```
logging {
  level  = "info"
  format = "logfmt"
}
```

config.river

```
module.file "this" {
  filename = "module.river"
}
```

I may aware that it make no sense to have a logging configuration in a submodule, but a go panic should never be happen.

```
jok@CDT-MB-20200178 flow-remote-configuration % ~/Downloads/grafana-agent/build/grafana-agent-flow run init.river 
ts=2023-04-25T15:38:35.12018Z level=info msg="now listening for http traffic" addr=127.0.0.1:12345
ts=2023-04-25T15:38:35.120329Z level=info msg="running usage stats reporter"
ts=2023-04-25T15:38:35.121413Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="starting complete graph evaluation"
ts=2023-04-25T15:38:35.121425Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished node evaluation" node_id=logging duration=2µs
ts=2023-04-25T15:38:35.122096Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished node evaluation" node_id=module.file.config duration=665.25µs
ts=2023-04-25T15:38:35.122102Z level=info trace_id=76cd1ec5d91abb34b4172bffe072e7a2 msg="finished complete graph evaluation" duration=736.584µs
ts=2023-04-25T15:38:35.122155Z level=info msg="http server closed" addr=127.0.0.1:12345 err="http: Server closed"
ts=2023-04-25T15:38:35.122172Z level=error msg="failed to start reporter" err="context canceled"
ts=2023-04-25T15:38:35.122173Z level=info msg="http server closed" addr=memory err="http: Server closed"
interrupt received
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1029f32d0]

goroutine 1 [running]:
github.com/grafana/agent/pkg/flow/internal/controller.(*LoggingConfigNode).NodeID(0x78?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/config_logging.go:93
github.com/grafana/agent/pkg/flow/internal/dag.(*Graph).Add(0x140010f1ac8, {0x106ffa220?, 0x0})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/dag/dag.go:69 +0x148
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).populateConfigBlockNodes(0x140005fde60, 0x1007cad1c?, {0x140006ba640, 0x1, 0x20?})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:251 +0x61c
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).loadNewGraph(0x140005fde60, 0x1007ca408?, {0x0, 0x0, 0x0}, {0x140006ba640?, 0x140010f1b98?, 0x1007cad1c?})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:202 +0x50
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x140005fde60, 0x14000f2aae0, {0x0?, 0x0, 0x0}, {0x140006ba640, 0x1, 0x1})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:105 +0x150
github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x14000f9b790, 0x14000f2ca20, 0x14000eb8880?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/flow.go:279 +0x364
github.com/grafana/agent/component/module.(*ModuleComponent).LoadFlowContent(0x14000f9b860, 0x10699c100?, {0x14000eb8840?, 0x1?})
        /Users/jok/Downloads/grafana-agent/component/module/module.go:77 +0x144
github.com/grafana/agent/component/module/file.(*Component).Update(0x14000db1700, {0x106685600?, 0x140010f23a0?})
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:147 +0x168
github.com/grafana/agent/component/module/file.New({{0x140008cbbc0, 0x12}, 0x140002fdc20, {0x14000faa080, 0x1d}, 0x14000f2a720, {0x107036b90, 0x14000fac0f0}, {0x106ffa280, 0x14000cb9a40}, ...}, ...)
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:86 +0x20c
github.com/grafana/agent/component/module/file.init.0.func1({{0x140008cbbc0, 0x12}, 0x140002fdc20, {0x14000faa080, 0x1d}, 0x14000f2a720, {0x107036b90, 0x14000fac0f0}, {0x106ffa280, 0x14000cb9a40}, ...}, ...)
        /Users/jok/Downloads/grafana-agent/component/module/file/file.go:24 +0xf4
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).evaluate(0x14000d0d200, 0x0?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/component.go:308 +0x474
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).Evaluate(0x140003e0c80?, 0x14000f2a6e0?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/component.go:246 +0x20
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).evaluate(0x14000e38c60, {0x106ff80c0, 0x140002fdd10}, 0x1047a1bb6?, {0x107032cf0, 0x14000d0d200})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:467 +0x54
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply.func2({0x106ffa1e0, 0x14000d0d200})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:148 +0x4c8
github.com/grafana/agent/pkg/flow/internal/dag.WalkTopological(0x14000cb99e0, {0x140003e10c0, 0x3, 0x2?}, 0x140010f3250)
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/dag/walk.go:110 +0x180
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x14000e38c60, 0x14000f2a6e0, {0x140006ba610?, 0x1, 0x1}, {0x0, 0x0, 0x0})
        /Users/jok/Downloads/grafana-agent/pkg/flow/internal/controller/loader.go:131 +0x7b0
github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x14000f9ad00, 0x14000f2c480, 0x140010f35f8?)
        /Users/jok/Downloads/grafana-agent/pkg/flow/flow.go:279 +0x364
github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run.func3()
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:192 +0x120
github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run(0x140000e3b20, {0x16f643888, 0xa})
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:297 +0x10d0
github.com/grafana/agent/cmd/internal/flowmode.runCommand.func1(0x140005dd800?, {0x140006b94c0?, 0x1?, 0x1?})
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/cmd_run.go:81 +0x38
github.com/spf13/cobra.(*Command).execute(0x140005dd800, {0x140006b9470, 0x1, 0x1})
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140005dcc00)
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jok/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/grafana/agent/cmd/internal/flowmode.Run()
        /Users/jok/Downloads/grafana-agent/cmd/internal/flowmode/flowmode.go:31 +0x198
main.main()
        /Users/jok/Downloads/grafana-agent/cmd/grafana-agent-flow/main.go:32 +0x1c
```

**Comment by rfratto** [comment]
Thanks, it's supposed to reject logging blocks in modules, but it looks like there's a bug somewhere.

**Comment by mattdurham** [comment]
Agreed, it should fail not panic.

**Comment by erikbaranowski** [comment]
Agreed. I am working on some refactoring related to making the argument block a config block internally. I just refactored and tested this specific case so it should be fixed once I finish work and we merge https://github.com/grafana/agent/pull/3592

I am looking to add tests to validate each of the validation scenarios so we should hopefully have something in the automation that would catch something like this when I am done.
