### ISSUE TITLE
ServiceMonitors integration crashed when specifying multiple namespaces

### ISSUE THREAD

**Issue by malmor** [grafana/agent#4142]
### What's wrong?

Hey there,
we have just upgraded our `grafana-agent` deployment to version v0.34.0 in order to utilize the new `prometheus.operator.servicemonitors` integration.

This works like a charm when using the default configuration (scraping all `ServiceMonitor` resources in all namespaces). But we have some monitors that we currently do not want to scrape - so we used the `namespaces` argument to exclude them.

When specifying more than one namespace the agent crashes and does not recover.

I tested a few different scenarios:
- Default configuration (all namespaces, some of them containing monitors)
  - ```
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
    }
    ```
  - No problem here, everything works like a charm
- Specifying a single namespace that does not contain a monitor
  - ```
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
        namespaces = ["my-empty-namespace"]
    }
    ```
  - No problem here, everything works like a charm (as expected no metrics are being scraped)
- Specifying a single namespace that does contain a monitor
  - ```
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
        namespaces = ["my-app"]
    }
    ```
  - No problem here, everything works like a charm and metrics are being scraped
- Specifying two namespaces that both do not contain a monitor
  - ```
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
        namespaces = ["my-empty-namespace-1", "my-empty-namespace-2"]
    }
    ```
  - No problem here, everything works like a charm (as expected no metrics are being scraped)
- Specifying two namespaces where atlease one contains a monitor
  - ```
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
        namespaces = ["my-app", "my-empty-namespace-2"]
    }
    ```
  - The agent crashes and does not recover from it

I followed the documentation in [prometheus.operator.servicemonitors](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.operator.servicemonitors/#arguments) which also contains an example with a single namespace: [prometheus.operator.servicemonitors example](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.operator.servicemonitors/#example)

### Steps to reproduce

Install the `grafana-agent` helm chart into a cluster with multiple namespaces, where atlease some of them contain `ServiceMonitor` resources.

Then specify the new `prometheus.operator.servicemonitors` integration and limit its scope to two namespaces (where atleast one contains a monitor).

Take a look at the pod - this should be failing with the stack trace provided below.

### System information

Windows 10 22H2  //  k3d v5.4.6  //  k3s version v1.24.4-k3s1

### Software version

Grafana Agent v0.34.0

### Configuration

```text
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-configuration
data:
  config.river: |-
    // Runtime configuration
    logging {
    	level  = "info"
    	format = "logfmt"
    }

    // Configure agent to scrape metrics from all discovered servicemonitors
    prometheus.operator.servicemonitors "servicemonitors" {
        forward_to = [prometheus.remote_write.default.receiver]
        namespaces = ["default", "my-app"]
    }

    // Configure remote write for mimir
    prometheus.remote_write "default" {
      endpoint {
        url = "http://host.k3d.internal:9009/api/prom/push"
      }
    }
```

### Logs

```text
### Test - Using a single namespace that has no monitors
ts=2023-06-13T10:20:15.4593876Z level=info msg="now listening for http traffic" addr=0.0.0.0:80
ts=2023-06-13T10:20:15.4602233Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="starting complete graph evaluation"
ts=2023-06-13T10:20:15.4774212Z component=prometheus.remote_write.default level=info subcomponent=wal msg="replaying WAL, this may take a while" dir=/tmp/agent/prometheus.remote_write.default/wal
ts=2023-06-13T10:20:15.4822677Z component=prometheus.remote_write.default level=info subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-06-13T10:20:15.4848751Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting WAL watcher" queue=96e9ac     
ts=2023-06-13T10:20:15.4850484Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting scraped metadata watcher"     
ts=2023-06-13T10:20:15.4851005Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="finished node evaluation" node_id=prometheus.remote_write.default duration=24.7411ms
ts=2023-06-13T10:20:15.4852846Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="finished node evaluation" node_id=prometheus.operator.servicemonitors.servicemonitors duration=127µs
ts=2023-06-13T10:20:15.4854153Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="finished node evaluation" node_id=tracing duration=23.7µs
ts=2023-06-13T10:20:15.485455Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Replaying WAL" queue=96e9ac
ts=2023-06-13T10:20:15.485513Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="finished node evaluation" node_id=logging duration=55.6µs
ts=2023-06-13T10:20:15.485638Z level=info trace_id=003026d0cbd0e26ef2b018f07d307413 msg="finished complete graph evaluation" duration=25.722ms
ts=2023-06-13T10:20:15.4858634Z level=info msg="scheduling loaded components"
ts=2023-06-13T10:20:15.4876357Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="Using pod service account via in-cluster config"
ts=2023-06-13T10:20:15.6525324Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="informers  started"



### Test - Using a single namespace that has a monitor
ts=2023-06-13T10:22:20.4031825Z level=info msg="now listening for http traffic" addr=0.0.0.0:80
ts=2023-06-13T10:22:20.4040901Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="starting complete graph evaluation"
ts=2023-06-13T10:22:20.4093907Z component=prometheus.remote_write.default level=info subcomponent=wal msg="replaying WAL, this may take a while" dir=/tmp/agent/prometheus.remote_write.default/wal
ts=2023-06-13T10:22:20.4109263Z component=prometheus.remote_write.default level=info subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-06-13T10:22:20.4134054Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting WAL watcher" queue=96e9ac     
ts=2023-06-13T10:22:20.4134587Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting scraped metadata watcher"     
ts=2023-06-13T10:22:20.4135067Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="finished node evaluation" node_id=prometheus.remote_write.default duration=9.3421ms
ts=2023-06-13T10:22:20.4137412Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="finished node evaluation" node_id=prometheus.operator.servicemonitors.servicemonitors duration=190.5µs
ts=2023-06-13T10:22:20.4137758Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Replaying WAL" queue=96e9ac
ts=2023-06-13T10:22:20.4138127Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="finished node evaluation" node_id=tracing duration=17.1µs
ts=2023-06-13T10:22:20.413859Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="finished node evaluation" node_id=logging duration=30.8µs
ts=2023-06-13T10:22:20.4138725Z level=info trace_id=9104f4643986247ad280a2010b6a57dc msg="finished complete graph evaluation" duration=10.4767ms
ts=2023-06-13T10:22:20.4139701Z level=info msg="scheduling loaded components"
ts=2023-06-13T10:22:20.4142426Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="Using pod service account via in-cluster config"
ts=2023-06-13T10:22:20.5497625Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="informers  started"
ts=2023-06-13T10:22:20.5499766Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="found pod monitor" name=my-app-metrics
ts=2023-06-13T10:22:20.5614487Z component=prometheus.operator.servicemonitors.servicemonitors level=info discovery=kubernetes config=serviceMonitor/my-app/my-app-metrics/0 msg="Using pod service account via in-cluster config"



### Test - Using two namespaces that have no monitors
ts=2023-06-13T10:28:20.5823089Z level=info msg="now listening for http traffic" addr=0.0.0.0:80
ts=2023-06-13T10:28:20.5826185Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="starting complete graph evaluation"
ts=2023-06-13T10:28:20.5883888Z component=prometheus.remote_write.default level=info subcomponent=wal msg="replaying WAL, this may take a while" dir=/tmp/agent/prometheus.remote_write.default/wal
ts=2023-06-13T10:28:20.5888282Z component=prometheus.remote_write.default level=info subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-06-13T10:28:20.5894866Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting WAL watcher" queue=96e9ac     
ts=2023-06-13T10:28:20.5895452Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting scraped metadata watcher"     
ts=2023-06-13T10:28:20.5895825Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="finished node evaluation" node_id=prometheus.remote_write.default duration=6.8987ms
ts=2023-06-13T10:28:20.5897542Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="finished node evaluation" node_id=prometheus.operator.servicemonitors.servicemonitors duration=132.4µs
ts=2023-06-13T10:28:20.5898335Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="finished node evaluation" node_id=tracing duration=18.2µs
ts=2023-06-13T10:28:20.5898648Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Replaying WAL" queue=96e9ac
ts=2023-06-13T10:28:20.5899074Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="finished node evaluation" node_id=logging duration=51.6µs
ts=2023-06-13T10:28:20.5900016Z level=info trace_id=7ab2135c26b2dc17322db2e3c8a68075 msg="finished complete graph evaluation" duration=7.4525ms
ts=2023-06-13T10:28:20.5901142Z level=info msg="scheduling loaded components"
ts=2023-06-13T10:28:20.5904406Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="Using pod service account via in-cluster config"
ts=2023-06-13T10:28:20.8393006Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="informers  started"



### Test - Using two namespaces where one has a monitor
ts=2023-06-13T10:30:07.9226185Z level=info msg="now listening for http traffic" addr=0.0.0.0:80
ts=2023-06-13T10:30:07.9228506Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="starting complete graph evaluation"
ts=2023-06-13T10:30:07.922907Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="finished node evaluation" node_id=tracing duration=5.2µs
ts=2023-06-13T10:30:07.9229859Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="finished node evaluation" node_id=logging duration=31µs
ts=2023-06-13T10:30:07.9274188Z component=prometheus.remote_write.default level=info subcomponent=wal msg="replaying WAL, this may take a while" dir=/tmp/agent/prometheus.remote_write.default/wal
ts=2023-06-13T10:30:07.9276358Z component=prometheus.remote_write.default level=info subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-06-13T10:30:07.9281482Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting WAL watcher" queue=96e9ac     
ts=2023-06-13T10:30:07.9281884Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Starting scraped metadata watcher"     
ts=2023-06-13T10:30:07.928209Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="finished node evaluation" node_id=prometheus.remote_write.default duration=5.2124ms
ts=2023-06-13T10:30:07.9282797Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="finished node evaluation" node_id=prometheus.operator.servicemonitors.servicemonitors duration=53.7µs
ts=2023-06-13T10:30:07.9282904Z level=info trace_id=8876e2d43ee596bc029501337049fc80 msg="finished complete graph evaluation" duration=5.5012ms
ts=2023-06-13T10:30:07.9284099Z level=info msg="scheduling loaded components"
ts=2023-06-13T10:30:07.928486Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=96e9ac url=http://host.k3d.internal:9009/api/prom/push msg="Replaying WAL" queue=96e9ac
ts=2023-06-13T10:30:07.9287135Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="Using pod service account via in-cluster config"
ts=2023-06-13T10:30:08.0508224Z component=prometheus.operator.servicemonitors.servicemonitors level=info msg="found pod monitor" name=my-app-metrics
ts=2023-06-13T10:30:08.0520334Z component=prometheus.operator.servicemonitors.servicemonitors level=info discovery=kubernetes config=serviceMonitor/my-app/my-app-metrics/0 msg="Using pod service account via in-cluster config"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1ad9800]

goroutine 71 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x3b?})
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x5828cc0, 0xab14230})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/prometheus/prometheus/scrape.(*Manager).ApplyConfig(0x0, 0xc001257828)
        /go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20230511165250-22c61d1811b2/scrape/manager.go:270 +0x60
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).apply(0xc0015a6000)
        /src/agent/component/prometheus/operator/common/crdmanager.go:249 +0x3a5
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).addServiceMonitor(0xc0015a6000, 0xc000e881e0)
        /src/agent/component/prometheus/operator/common/crdmanager.go:347 +0x565
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).onAddServiceMonitor(0xc0015a6000, {0x64b1f20?, 0xc000e881e0})
        /src/agent/component/prometheus/operator/common/crdmanager.go:356 +0x15d
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/shared_informer.go:911 +0x134
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00073c738?, {0x746eca0, 0xc001546750}, 0x1, 0xc00120a300)
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00073c7a0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000e06b00)
        /go/pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/shared_informer.go:905 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:75 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:73 +0x85
```

**Comment by captncraig** [comment]
Thank you for your detailed reproduction. I believe it is from starting things up in the wrong order.
