### ISSUE TITLE
SNMP exporter panic

### ISSUE THREAD

**Issue by mateuszdrab** [grafana/agent#4720]
### What's wrong?

The agent crashes during startup
Not sure if this is better off here or in https://github.com/prometheus/snmp_exporter

### Steps to reproduce

Deploy the below configuration; when SNMP exporter is commented out, everything works fine.

### System information

6.1.21-v8 arm64

### Software version

v0.35.2

### Configuration

```text
snmp:
    enabled: true
    relabel_configs:
      - action: replace
        regex: (^.*snmp)\/(.*)
        replacement: $2
        source_labels:
          - job
        target_label: target
      - action: replace
        regex: (^.*snmp)\/(.*)
        replacement: $1
        source_labels:
          - job
        target_label: job
    snmp_targets:
      - name: hallway-ap
        address: 192.168.0.43
        module: if_mib
        walk_params: public
      - name: vm-hub
        address: 192.168.0.1
        module: if_mib
        walk_params: public
    walk_params:
      public:
        auth:
          community: public
        version: 2
```

### Logs

```text
2023-08-07T12:02:52+01:00	panic: runtime error: invalid memory address or nil pointer dereference
2023-08-07T12:02:52+01:00	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48284b0]
2023-08-07T12:02:52+01:00	
2023-08-07T12:02:52+01:00	goroutine 33445 [running]:
2023-08-07T12:02:52+01:00	github.com/prometheus/snmp_exporter/collector.ScrapeTarget({0x76037d0?, 0x40026be630}, {0x40053590b4, 0xb}, 0x40059e7560, 0x4005194980, {0x759db60, 0x40048fe960}, {{0x7619d28, 0x4006175c80}, ...})
2023-08-07T12:02:52+01:00		/go/pkg/mod/github.com/prometheus/snmp_exporter@v0.22.1-0.20230623130038-562ae9055ce3/collector/collector.go:95 +0xe0
2023-08-07T12:02:52+01:00	github.com/prometheus/snmp_exporter/collector.Collector.Collect({{0x76037d0, 0x40026be630}, {0x40053590b4, 0xb}, 0x40059e7560, 0x4005194980, {0x759db60, 0x40048fe960}, {{0x7619d28, 0x4006175c80}, ...}}, ...)
2023-08-07T12:02:52+01:00		/go/pkg/mod/github.com/prometheus/snmp_exporter@v0.22.1-0.20230623130038-562ae9055ce3/collector/collector.go:407 +0xd4
2023-08-07T12:02:52+01:00	github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
2023-08-07T12:02:52+01:00		/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:455 +0xd8
2023-08-07T12:02:52+01:00	created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
2023-08-07T12:02:52+01:00		/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:547 +0x99c
```

**Comment by marctc** [comment]
You are using the older config format for snmp integration. Please take a look at the new one: https://grafana.com/docs/agent/latest/static/configuration/integrations/snmp-config/

**Comment by mateuszdrab** [comment]
Oh no, breaking changes 😏
That seems to have done the trick.
Thanks @marctc

**Comment by marctc** [comment]
> Oh no, sneaky breaking changes smirk .

We documented those changes in CHANGELOG and https://grafana.com/docs/agent/latest/static/upgrade-guide/#v035. So not so sneaky IMO. If you have specific feedback how better address those, please let us know!

**Comment by mateuszdrab** [comment]
> > Oh no, sneaky breaking changes smirk .
> 
> We documented those changes in CHANGELOG and https://grafana.com/docs/agent/latest/static/upgrade-guide/#v035. So not so sneaky IMO. If you have specific feedback how better address those, please let us know! 
> 

True, my bad. 

It sneaked through my guards. I run lots of stuff on auto updates and have new release notifications on to keep track of changes like this. 

Changes like this are inevitable so I understand, maybe some deprecation notice would help or even a panic with a more helpful message.
