### ISSUE TITLE
Agent crashes with minimal blackbox configuration

### ISSUE THREAD

**Issue by pschiffe** [grafana/agent#4798]
### What's wrong?

Grafana agent crashes when trying to load blackbox exporter.

### Steps to reproduce

Fedora 38, aarch64. Install grafana agent from official grafana repo and try to use provided configuration.

### System information

Fedora 38, kernel 6.4.10-200.fc38.aarch64

### Software version

grafana-agent-flow-0.35.3-1.aarch64

### Configuration

```text
# cat /etc/grafana-agent-flow.river 
// For a full configuration reference, see https://grafana.com/docs/agent/latest/flow/
logging {
  level = "info"
}

prometheus.exporter.blackbox "default" {
  config_file = "/etc/grafana-agent-flow-blackbox.yaml"

  target "traefik" {
    address = "http://127.0.0.1:8082/ping"
    module  = "http_2xx_example"
  }

}

prometheus.scrape "default" {
  targets = [prometheus.exporter.blackbox.default.targets]

  scrape_interval = "15s"
  forward_to = [prometheus.remote_write.default.receiver]
}

prometheus.remote_write "default" {
  endpoint {
    url = "http://somewhere:9090/api/v1/write"

    basic_auth {
      username = "user"
      password = "pw"
    }
  }
}




# cat /etc/grafana-agent-flow-blackbox.yaml 
modules:
  http_2xx_example:
    prober: http
    timeout: 5s
```

### Logs

```text
Aug 14 20:02:11 host systemd[1]: Started grafana-agent-flow.service - Vendor-neutral programmable observability pipelines..
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.992816292Z level=info boringcryptoenabled=false
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.993430456Z level=info controller_id= trace_id=c5ec422843b34734d10ea58faed2c270 msg="starting complete graph evaluation"
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.993750578Z level=info controller_id= trace_id=c5ec422843b34734d10ea58faed2c270 msg="finished node evaluation" node_id=prometheus.exporter.blackbox.default duration=227.641µs
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.993834339Z level=info controller_id= trace_id=c5ec422843b34734d10ea58faed2c270 msg="finished complete graph evaluation" duration=465.403µs
Aug 14 20:02:11 host grafana-agent-flow[9445]: interrupt received
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.99395342Z level=info service=http msg="now listening for http traffic" addr=127.0.0.1:12345
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.994160261Z level=info service=http msg="http server closed" addr=127.0.0.1:12345 err="http: Server closed"
Aug 14 20:02:11 host grafana-agent-flow[9445]: ts=2023-08-14T20:02:11.994190221Z level=info service=http msg="http server closed" addr=memory err="http: Server closed"
Aug 14 20:02:11 host grafana-agent-flow[9445]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 14 20:02:11 host grafana-agent-flow[9445]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x3744dfc]
Aug 14 20:02:11 host grafana-agent-flow[9445]: goroutine 1 [running]:
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/prometheus/blackbox_exporter/config.(*SafeConfig).ReloadConfig.func1()
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /go/pkg/mod/github.com/prometheus/blackbox_exporter@v0.24.1-0.20230623125439-bd22efa1c900/config/config.go:113 +0x4c
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/prometheus/blackbox_exporter/config.(*SafeConfig).ReloadConfig(0x4000841280, {0x40022e48d1, 0x25}, {0x754ae80, 0x4002301360})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /go/pkg/mod/github.com/prometheus/blackbox_exporter@v0.24.1-0.20230623125439-bd22efa1c900/config/config.go:145 +0x570
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/integrations/blackbox_exporter.loadFile({0x40022e48d1, 0x25}, {0x754ae80, 0x4002301360})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/integrations/blackbox_exporter/blackbox_exporter.go:26 +0x84
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/integrations/blackbox_exporter.LoadBlackboxConfig({0x754ae80?, 0x4002301360?}, {0x40022e48d1, 0x25}, {0x4002329980, 0x1, 0x38?}, 0x5eb5500?)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/integrations/blackbox_exporter/blackbox_exporter.go:81 +0x5c
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/integrations/blackbox_exporter.New({0x754ae80?, 0x4002301360}, 0x4000841240)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/integrations/blackbox_exporter/blackbox_exporter.go:99 +0x48
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/integrations/blackbox_exporter.(*Config).NewIntegration(...)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/integrations/blackbox_exporter/blackbox_exporter.go:68
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/component/prometheus/exporter/blackbox.createExporter({{0xffff68322c18, 0x4002328d20}, {0x40022e4990, 0x24}, {0x754ae80, 0x4002301360}, {0x40022b7940, 0x40}, 0x4002309150, {0x7598380, ...}, ...}, ...)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/component/prometheus/exporter/blackbox/blackbox.go:30 +0x2e4
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/component/prometheus/exporter.(*Component).Update(0x400087b5e0, {0x6009520, 0x4002301810})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/component/prometheus/exporter/exporter.go:86 +0x90
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/component/prometheus/exporter.newExporter.func1({{0xffff68322c18, 0x4002328d20}, {0x40022e4990, 0x24}, {0x754ae80, 0x4002301360}, {0x40022b7940, 0x40}, 0x4002309150, {0x7598380, ...}, ...}, ...)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/component/prometheus/exporter/exporter.go:142 +0x478
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).evaluate(0x400231c500, 0x0?)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/controller/component.go:325 +0x434
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).Evaluate(0x4002300af0?, 0x417b10?)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/controller/component.go:263 +0x20
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).evaluate(0x40023072c0, {0x754ae80, 0x40023016d0}, {0x7594180, 0x400231c500})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/controller/loader.go:490 +0x54
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply.func2({0x754df60, 0x400231c500})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/controller/loader.go:156 +0x4a4
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/dag.WalkTopological(0x4000610de0, {0x4000841100, 0x4, 0x2?}, 0x400171f2d8)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/dag/walk.go:110 +0x180
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).Apply(0x40023072c0, 0x1?, {0x4000610dc0?, 0x3, 0x4}, {0x40009093a0, 0x1, 0x1})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/internal/controller/loader.go:139 +0x7fc
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/pkg/flow.(*Flow).LoadFile(0x400087b260, 0x40023012c0, 0x65c2b3f?)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/pkg/flow/flow.go:268 +0xbc
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run.func4()
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/cmd/internal/flowmode/cmd_run.go:208 +0x130
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/cmd/internal/flowmode.(*flowRun).Run(0x40008234d0, {0xffffc6fa4e49, 0x1d})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/cmd/internal/flowmode/cmd_run.go:272 +0xac8
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/cmd/internal/flowmode.runCommand.func1(0x400069fb00?, {0x40023284b0?, 0x3?, 0x3?})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/cmd/internal/flowmode/cmd_run.go:79 +0x38
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/spf13/cobra.(*Command).execute(0x400069fb00, {0x4002328420, 0x3, 0x3})
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c4
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/spf13/cobra.(*Command).ExecuteC(0x400069f200)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/spf13/cobra.(*Command).Execute(...)
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
Aug 14 20:02:11 host grafana-agent-flow[9445]: github.com/grafana/agent/cmd/internal/flowmode.Run()
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/cmd/internal/flowmode/flowmode.go:33 +0x2dc
Aug 14 20:02:11 host grafana-agent-flow[9445]: main.main()
Aug 14 20:02:11 host grafana-agent-flow[9445]:         /drone/src/cmd/grafana-agent-flow/main.go:27 +0x1c
Aug 14 20:02:12 host systemd[1]: grafana-agent-flow.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 14 20:02:12 host systemd[1]: grafana-agent-flow.service: Failed with result 'exit-code'.
```

**Comment by marctc** [comment]
Hey, thanks for reporting. I'm able to reproduce it, I'm looking into it.
