### ISSUE TITLE
Nil pointer dereference when PodMonitor scraping enabled

### ISSUE THREAD

**Issue by rknightion** [grafana/agent#5071]
### What's wrong?

I thought at first I was experiencing https://github.com/grafana/agent/issues/4142 but we're on agent ver v0.35.2 (from the grafana/k8s-monitoring chart) and also not filtering by namespace and this seems to be failing on PodMonitors.

Upon deleting the 3 pod monitors present in the cluster, the agent starts successfully. When deleting them one at a time it didn't seem to fail on a specific PodMonitor as we had monitors from different projects there. The presence of the PodMonitor seemed to lead to the failure. 

### Steps to reproduce

Start the agent with ServiceMonitor scraping enabled in a cluster with some PodMonitors

### System information

EKS 1.24

### Software version

v0.35.2

### Configuration

```text
This is mostly auto generated by k8s-monitoring chart with the following enabled in the charts values file:
metrics:
  enabled: true
  podMonitors:
    enabled: true
  serviceMonitors:
    # -- Include service discovery for ServiceMonitor objects
    enabled: true


Full config:
discovery.kubernetes "nodes" {
  role = "node"
}
    
discovery.kubernetes "pods" {
  role = "pod"
}
    
discovery.kubernetes "services" {
  role = "service"
}
    
// Grafana Agent
discovery.relabel "agent" {
  targets = discovery.kubernetes.services.targets
  rule {
    source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
    regex = "grafana-agent"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_name"]
    regex = "grafana-agent"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_service_port_name"]
    regex = "http-metrics"
    action = "keep"
  }
}

prometheus.scrape "agent" {
  job_name   = "integrations/agent"
  targets  = discovery.relabel.agent.output
  forward_to = [prometheus.relabel.agent.receiver]
  clustering {
    enabled = true
  }
}

prometheus.relabel "agent" {
  rule {
    source_labels = ["__name__"]
    regex = "up|agent_build_info"
    action = "keep"
  }
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// Kubelet
discovery.relabel "kubelet" {
  targets = discovery.kubernetes.nodes.targets
  rule {
    target_label = "__address__"
    replacement  = "kubernetes.default.svc.cluster.local:443"
  }
  rule {
    source_labels = ["__meta_kubernetes_node_name"]
    regex         = "(.+)"
    replacement   = "/api/v1/nodes/${1}/proxy/metrics"
    target_label  = "__metrics_path__"
  }
  rule {
    target_label = "job"
    replacement = "kubelet"
  }
}

prometheus.scrape "kubelet" {
  job_name   = "integrations/kubernetes/kubelet"
  targets  = discovery.relabel.kubelet.output
  scheme   = "https"
  bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  tls_config {
    insecure_skip_verify = true
  }
  clustering {
    enabled = true
  }
  forward_to = [prometheus.relabel.kubelet.receiver]
}

prometheus.relabel "kubelet" {
  rule {
    source_labels = ["__name__"]
    regex = "up|container_cpu_usage_seconds_total|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_certificate_manager_client_ttl_seconds|kubelet_certificate_manager_server_ttl_seconds|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_cgroup_manager_duration_seconds_count|kubelet_node_config_error|kubelet_node_name|kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_bucket|kubelet_pod_start_duration_seconds_bucket|kubelet_pod_start_duration_seconds_count|kubelet_pod_worker_duration_seconds_bucket|kubelet_pod_worker_duration_seconds_count|kubelet_running_container_count|kubelet_running_containers|kubelet_running_pod_count|kubelet_running_pods|kubelet_runtime_operations_errors_total|kubelet_runtime_operations_total|kubelet_server_expiration_renew_errors|kubelet_volume_stats_available_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_inodes|kubelet_volume_stats_inodes_used|kubernetes_build_info|namespace_workload_pod|rest_client_requests_total|storage_operation_duration_seconds_count|storage_operation_errors_total|volume_manager_total_volumes"
    action = "keep"
  }
  rule {
    target_label = "job"
    replacement = "kubelet"
  }
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// cAdvisor
discovery.relabel "cadvisor" {
  targets = discovery.kubernetes.nodes.targets
  rule {
    target_label = "__address__"
    replacement  = "kubernetes.default.svc.cluster.local:443"
  }
  rule {
    source_labels = ["__meta_kubernetes_node_name"]
    regex         = "(.+)"
    replacement   = "/api/v1/nodes/${1}/proxy/metrics/cadvisor"
    target_label  = "__metrics_path__"
  }
  rule {
    target_label = "job"
    replacement = "cadvisor"
  }
}

prometheus.scrape "cadvisor" {
  job_name   = "integrations/kubernetes/cadvisor"
  targets    = discovery.relabel.cadvisor.output
  scheme     = "https"
  bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  tls_config {
    insecure_skip_verify = true
  }
  clustering {
    enabled = true
  }
  forward_to = [prometheus.relabel.cadvisor.receiver]
}

prometheus.relabel "cadvisor" {
  rule {
    source_labels = ["__name__"]
    regex = "up|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_usage_seconds_total|container_fs_reads_bytes_total|container_fs_reads_total|container_fs_writes_bytes_total|container_fs_writes_total|container_memory_cache|container_memory_rss|container_memory_swap|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_bytes_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total|machine_memory_bytes"
    action = "keep"
  }
  rule {
    target_label = "job"
    replacement = "cadvisor"
  }
  rule {
    source_labels = ["__name__","image"]
    separator = "@"
    regex = "(container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*)@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__","container"]
    separator = "@"
    regex = "(container_cpu_.*|container_fs_.*|container_memory_.*)@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
    target_label = "id"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
    target_label = "image"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
    target_label = "name"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "machine_memory_bytes"
    target_label = "boot_id"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "machine_memory_bytes"
    target_label = "system_uuid"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__", "device"]
    separator = "@"
    regex = "container_fs_.*@(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dasd.+)"
    target_label = "__keepme"
    replacement = "1"
  }
  rule {
    source_labels = ["__name__", "__keepme"]
    separator = "@"
    regex = "container_fs_.*@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "container_fs_.*"
    target_label = "__keepme"
    replacement = ""
  }
  
  rule {
    source_labels = ["__name__", "interface"]
    separator = "@"
    regex = "container_network_.*@(en[ospx]|wlan|eth)[0-9].*"
    target_label = "__keepme"
    replacement = "1"
  }
  rule {
    source_labels = ["__name__", "__keepme"]
    separator = "@"
    regex = "container_network_.*@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "container_network_.*"
    target_label = "__keepme"
    replacement = ""
  }
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// Kube State Metrics
discovery.relabel "kube_state_metrics" {
  targets = discovery.kubernetes.services.targets
  rule {
    source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
    regex = "grafana-agent"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_name"]
    regex = "kube-state-metrics"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_service_port_name"]
    regex = "http"
    action = "keep"
  }
  rule {
    target_label = "job"
    replacement = "kube-state-metrics"
  }
}

prometheus.scrape "kube_state_metrics" {
  job_name   = "integrations/kubernetes/kube-state-metrics"
  targets    = discovery.relabel.kube_state_metrics.output
  clustering {
    enabled = true
  }
  forward_to = [prometheus.relabel.kube_state_metrics.receiver]
}

prometheus.relabel "kube_state_metrics" {
  rule {
    source_labels = ["__name__"]
    regex = "up|kube_daemonset.*|kube_deployment_metadata_generation|kube_deployment_spec_replicas|kube_deployment_status_observed_generation|kube_deployment_status_replicas_available|kube_deployment_status_replicas_updated|kube_horizontalpodautoscaler_spec_max_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_status_desired_replicas|kube_job.*|kube_namespace_status_phase|kube_namespace_status_phase|kube_node.*|kube_persistentvolumeclaim_resource_requests_storage_bytes|kube_pod_container_info|kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_container_status_restarts_total|kube_pod_container_status_waiting_reason|kube_pod_container_status_waiting_reason|kube_pod_info|kube_pod_owner|kube_pod_start_time|kube_pod_status_phase|kube_pod_status_phase|kube_pod_status_reason|kube_replicaset.*|kube_resourcequota|kube_statefulset.*"
    action = "keep"
  }
  rule {
    target_label = "job"
    replacement = "kube-state-metrics"
  }
  rule {
    source_labels = ["__name__"]
    target_label = "uid"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    target_label = "image_id"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    target_label = "image"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    target_label = "image_spec"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_info|kube_pod_owner"
    target_label = "created_by_name"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_container_info"
    target_label = "container_id"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_info"
    target_label = "host_ip"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_info"
    target_label = "pod_ip"
    replacement = "NA"
  }
  rule {
    source_labels = ["__name__","reason"]
    separator = "@"
    regex = "kube_pod_status_reason@Evicted"
    target_label = "__keepme"
    replacement = "1"
  }
  rule {
    source_labels = ["__name__", "__keepme"]
    separator = "@"
    regex = "kube_pod_status_reason@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_status_reason"
    target_label = "__keepme"
    replacement = ""
  }
  rule {
    source_labels = ["__name__","phase"]
    separator = "@"
    regex = "kube_pod_status_phase@Unknown"
    target_label = "phase"
    replacement = "Failed"
  }
  rule {
    source_labels = ["__name__","phase"]
    separator = "@"
    regex = "kube_pod_status_phase@(Pending|Running|Failed)"
    target_label = "__keepme"
    replacement = "1"
  }
  rule {
    source_labels = ["__name__", "__keepme"]
    separator = "@"
    regex = "kube_pod_status_phase@"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_status_phase"
    target_label = "__keepme"
    replacement = ""
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_replicaset.*"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_.*(annotations|labels|created)"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_container_info"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_pod_container_status_restarts_total"
    action = "drop"
  }
  rule {
    source_labels = ["__name__"]
    regex = "kube_.*_status_replicas.*"
    action = "drop"
  }
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// Node Exporter
discovery.relabel "node_exporter" {
  targets = discovery.kubernetes.pods.targets
  rule {
    source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
    regex = "grafana-agent"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
    regex = "prometheus-node-exporter.*"
    action = "keep"
  }
  rule {
    source_labels = ["__meta_kubernetes_pod_node_name"]
    action = "replace"
    target_label = "instance"
  }
  rule {
    target_label = "job"
    replacement = "node-exporter"
  }
}

prometheus.scrape "node_exporter" {
  job_name   = "integrations/node_exporter"
  targets  = discovery.relabel.node_exporter.output
  clustering {
    enabled = true
  }
  forward_to = [prometheus.relabel.node_exporter.receiver]
}

prometheus.relabel "node_exporter" {
  rule {
    source_labels = ["__name__"]
    regex = "up|node_cpu.*|node_exporter_build_info|node_filesystem.*|node_memory.*|process_cpu_seconds_total|process_resident_memory_bytes"
    action = "keep"
  }
  rule {
    target_label = "job"
    replacement = "node-exporter"
  }
  rule {
    source_labels = ["__name__", "fstype"]
    separator = "@"
    regex = "node_filesystem.*@tmpfs"
    action = "drop"
  }
  rule {
    separator = "@"
    regex = "node_filesystem.*@/"
    source_labels = ["__name__","mountpoint"]
    target_label = "__keepme"
    replacement = "1"
  }
  rule {
    source_labels = ["__name__","__keepme"]
    separator = "@"
    regex = "node_filesystem.*@"
    action = "drop"
  }
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// PodMonitor
prometheus.operator.podmonitors "pod_monitors" {
  forward_to = [prometheus.relabel.podmonitors.receiver]
  clustering {
    enabled = true
  }
}

prometheus.relabel "podmonitors" {
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// ServiceMonitor
prometheus.operator.servicemonitors "service_monitors" {
  forward_to = [prometheus.relabel.servicemonitors.receiver]
  clustering {
    enabled = true
  }
}

prometheus.relabel "servicemonitors" {
  forward_to = [prometheus.remote_write.grafana_cloud_prometheus.receiver]
}
    
// Grafana Cloud Prometheus
local.file "prometheus_host" {
  filename  = "/etc/grafana-agent-credentials/prometheus_host"
}

local.file "prometheus_username" {
  filename  = "/etc/grafana-agent-credentials/prometheus_username"
}

local.file "prometheus_password" {
  filename  = "/etc/grafana-agent-credentials/prometheus_password"
  is_secret = true
}

local.file "prometheus_tenantid" {
  filename  = "/etc/grafana-agent-credentials/prometheus_tenantId"
}
prometheus.remote_write "grafana_cloud_prometheus" {
  endpoint {
    url = nonsensitive(local.file.prometheus_host.content) + "/api/v1/push"
    headers = { "X-Scope-OrgID" = local.file.prometheus_tenantid.content }

    basic_auth {
      username = local.file.prometheus_username.content
      password = local.file.prometheus_password.content
    }

  }
  external_labels = {
    customer = "redacted",
    envtype = "dev",
    mimircluster = "redacted",
    product = "redacted",
    cluster = "redacted",
  }
}
    
// Cluster Events
loki.source.kubernetes_events "cluster_events" {
  job_name   = "integrations/kubernetes/eventhandler"
  forward_to = [loki.write.grafana_cloud_loki.receiver]
}
    
// Grafana Cloud Loki
local.file "loki_host" {
  filename  = "/etc/grafana-agent-credentials/loki_host"
}

local.file "loki_username" {
  filename  = "/etc/grafana-agent-credentials/loki_username"
}

local.file "loki_password" {
  filename  = "/etc/grafana-agent-credentials/loki_password"
  is_secret = true
}

local.file "loki_tenantid" {
  filename  = "/etc/grafana-agent-credentials/loki_tenantId"
}
loki.write "grafana_cloud_loki" {
  endpoint {
    url = nonsensitive(local.file.loki_host.content) + "/loki/api/v1/push"
    tenant_id = local.file.loki_tenantid.content

    basic_auth {
      username = local.file.loki_username.content
      password = local.file.loki_password.content
    }
  }
  external_labels = {
    customer = "redacted",
    envtype = "dev",
    mimircluster = "redacted",
    product = "redacted",
    cluster = "redacted",
  }
}

mimir.rules.kubernetes "default" {
  address = "redacted"
  mimir_namespace_prefix = "redacted"
  tenant_id = "redacted"
  basic_auth {
    username = "redacted"
    password = "redacted"
  }
}
```

### Logs

```text
ts=2023-09-02T15:46:27.579534991Z level=info component=loki.source.kubernetes_events.cluster_events msg="watching events for namespace" namespace=
ts=2023-09-02T15:46:27.714407588Z level=info component=prometheus.operator.podmonitors.pod_monitors msg="informers  started"
ts=2023-09-02T15:46:27.714435229Z level=info component=prometheus.operator.podmonitors.pod_monitors msg="found pod monitor" name=linkerd-proxy
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x495e884]

goroutine 1095 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xffffb6a20f18?})
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x576b6e0, 0xb004ae0})
	/usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/grafana/agent/component/prometheus/operator/configgen.(*ConfigGenerator).GeneratePodMonitorConfig(_, _, {{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
	/src/agent/component/prometheus/operator/configgen/config_gen_podmonitor.go:197 +0x1634
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).addPodMonitor(0x4000281700, 0x400066efc0)
	/src/agent/component/prometheus/operator/common/crdmanager.go:370 +0x1bc
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).onAddPodMonitor(0x4000281700, {0x6500be0?, 0x400066efc0})
	/src/agent/component/prometheus/operator/common/crdmanager.go:394 +0x144
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/controller.go:243
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/shared_informer.go:973 +0x154
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xb392cc0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4003f87f28?, {0x75ab100, 0x400396cea0}, 0x1, 0x40023ce180)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40025bee40?, 0x3b9aca00, 0x0, 0xd0?, 0x40025bef00?)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0x400376fc20)
	/go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/shared_informer.go:967 +0x68
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/wait.go:72 +0x58
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/wait.go:70 +0x80
```

**Comment by hainenber** [comment]
Looks like this is fixed in #4813, which is landed in v0.36.0. Upgrading the agent would help with your case
