### ISSUE TITLE
Grafana Agent crashes when enabling PodMonitor operatorto pick up scrape configs that work on Prometheus Server

### ISSUE THREAD

**Issue by paul-bormans** [grafana/agent#5419]
### What's wrong?

We have seen grafana agent crashing with several different service-monitors as well as pod-monitors, the case described here is just one example:

`apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    monitoring: istio-proxies
    release: istio
  name: envoy-stats-monitor
  namespace: istio
spec:
  jobLabel: envoy-stats
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - interval: 15s
    path: /stats/prometheus
    relabelings:
    - action: keep
      regex: istio-proxy
      sourceLabels:
      - __meta_kubernetes_pod_container_name
    - action: keep
      sourceLabels:
      - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      sourceLabels:
      - __address__
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      targetLabel: __address__
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod_name
  selector:
    matchExpressions:
    - key: istio-prometheus-ignore
      operator: DoesNotExist
    - key: app.kubernetes.io/instance
      operator: NotIn
      values:
      - grafana-agent
`

Now obviously when there is an issue with a service-monitor or target, it should not crash the entire agent.

### Steps to reproduce

Enable service monitor operator and apply the provided sm yaml

### System information

Kubernetes GKE

### Software version

grafana/agent:v0.35.4, chart grafana-agent-0.24.0.tgz

### Configuration

```text
river config:

prometheus.operator.podmonitors "prometheus_podmonitor" {
  forward_to = [prometheus.relabel.pod_monitor.receiver]
}

prometheus.relabel "pod_monitor" {
	forward_to = [prometheus.remote_write.prom.receiver]
}

prometheus.remote_write "prom" {
	endpoint {
		url = "{{ .RemoteWriteEndpoint }}"
		headers = {
			"X-Scope-OrgID" = "{{ .tenant_id }}",
		}
	}
}
```

### Logs

```text
grafana-agent ts=2023-10-10T08:38:55.392282464Z level=info boringcryptoenabled=false
grafana-agent ts=2023-10-10T08:38:55.399951033Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="starting complete graph evaluation"
grafana-agent ts=2023-10-10T08:38:55.401730219Z level=info service=http msg="now listening for http traffic" addr=0.0.0.0:8888
grafana-agent ts=2023-10-10T08:38:55.40968512Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="replaying WAL, this may take a while" dir=/tmp/agent/prometheus.remote_write.prom/wal
grafana-agent ts=2023-10-10T08:38:55.410087299Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=0
grafana-agent ts=2023-10-10T08:38:55.412545694Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=fe3fe2 url=http://prometheus-ga.monitoring.svc.cluster.local:9090/api/v1/write msg="Starting WAL watcher" queue=fe3fe2
grafana-agent ts=2023-10-10T08:38:55.412581362Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=fe3fe2 url=http://prometheus-ga.monitoring.svc.cluster.local:9090/api/v1/write msg="Starting scraped metadata watcher"
grafana-agent ts=2023-10-10T08:38:55.412610818Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.remote_write.prom duration=12.613706ms
grafana-agent ts=2023-10-10T08:38:55.412913098Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.relabel.service_monitor duration=255.859┬╡s
grafana-agent ts=2023-10-10T08:38:55.413058816Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.operator.servicemonitors.prometheus_servicemonitor duration=109.765┬╡s
grafana-agent ts=2023-10-10T08:38:55.413495816Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.relabel.service duration=403.03┬╡s
grafana-agent ts=2023-10-10T08:38:55.415210579Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=fe3fe2 url=http://prometheus-ga.monitoring.svc.cluster.local:9090/api/v1/write msg="Replaying WAL" queue=fe3fe2
grafana-agent ts=2023-10-10T08:38:55.4167635Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.scrape.scrape_point duration=3.232996ms
grafana-agent ts=2023-10-10T08:38:55.417025685Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.relabel.pod_monitor duration=226.747┬╡s
grafana-agent ts=2023-10-10T08:38:55.417135574Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=prometheus.operator.podmonitors.prometheus_podmonitor duration=71.462┬╡s
grafana-agent ts=2023-10-10T08:38:55.417176355Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=tracing duration=21.576┬╡s
grafana-agent ts=2023-10-10T08:38:55.41721417Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished node evaluation" node_id=logging duration=22.348┬╡s
grafana-agent ts=2023-10-10T08:38:55.417246304Z level=info controller_id= trace_id=3c2d90410cfcaf1f8e6cea049bd666c5 msg="finished complete graph evaluation" duration=17.630174ms
grafana-agent ts=2023-10-10T08:38:55.417295806Z level=info msg="scheduling loaded components"
grafana-agent ts=2023-10-10T08:38:55.417670022Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-10-10T08:38:55.419708889Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-10-10T08:38:55.551692009Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor msg="informers  started"
grafana-agent ts=2023-10-10T08:38:55.55208326Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor msg="found service monitor" name=grafana
<...>
grafana-agent ts=2023-10-10T08:38:55.554110555Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor msg="found service monitor" name=cert-manager
grafana-agent ts=2023-10-10T08:38:55.554447415Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor msg="informers  started"
grafana-agent ts=2023-10-10T08:38:55.555143112Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor discovery=kubernetes config=serviceMonitor/cert-manager/cert-manager/0 msg="Using pod service account via in-cluster config"
<...>
grafana-agent ts=2023-10-10T08:38:55.554968457Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor msg="found pod monitor" name=cilium-agent
grafana-agent ts=2023-10-10T08:38:55.55727587Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor msg="found service monitor" name=cortex-distributor
grafana-agent ts=2023-10-10T08:38:55.562355161Z level=info component=prometheus.operator.servicemonitors.prometheus_servicemonitor discovery=kubernetes config=serviceMonitor/monitoring/cortex-distributor/0 msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-10-10T08:38:55.557334699Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor discovery=kubernetes config=podMonitor/kube-system/cilium-agent/0 msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-10-10T08:38:55.562895246Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor msg="found pod monitor" name=gatekeeper-audit
grafana-agent ts=2023-10-10T08:38:55.563307365Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor discovery=kubernetes config=podMonitor/gatekeeper/gatekeeper-audit/0 msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-10-10T08:38:55.563731254Z level=info component=prometheus.operator.podmonitors.prometheus_podmonitor msg="found pod monitor" name=envoy-stats-monitor
grafana-agent panic: runtime error: invalid memory address or nil pointer dereference [recovered]
grafana-agent     panic: runtime error: invalid memory address or nil pointer dereference
grafana-agent [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x524a45f]
grafana-agent 
grafana-agent goroutine 450 [running]:
grafana-agent k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:56 +0xd7
grafana-agent panic({0x60b0e40, 0xba628f0})
grafana-agent     /usr/local/go/src/runtime/panic.go:884 +0x213
grafana-agent github.com/grafana/agent/component/prometheus/operator/configgen.(*ConfigGenerator).GeneratePodMonitorConfig(_, _, {{0x0, 0x0}, 0x0, {0xc0026207c8, 0x11}, {0x0, 0x0}, 0x0, ...}, ...)
grafana-agent     /src/agent/component/prometheus/operator/configgen/config_gen_podmonitor.go:197 +0x1abf
grafana-agent github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).addPodMonitor(0xc0006a8c00, 0xc0002c5180)
grafana-agent     /src/agent/component/prometheus/operator/common/crdmanager.go:370 +0x26c
grafana-agent github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).onAddPodMonitor(0xc0006a8c00, {0x6e47960?, 0xc0002c5180})
grafana-agent     /src/agent/component/prometheus/operator/common/crdmanager.go:394 +0x15d
grafana-agent k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
grafana-agent     /go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/controller.go:243
grafana-agent k8s.io/client-go/tools/cache.(*processorListener).run.func1()
grafana-agent     /go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/shared_informer.go:973 +0x148
grafana-agent k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:226 +0x3e
grafana-agent k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002944738?, {0x7efd460, 0xc002611f20}, 0x1, 0xc0030942a0)
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:227 +0xb6
grafana-agent k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x10d7ca0?)
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:204 +0x89
grafana-agent k8s.io/apimachinery/pkg/util/wait.Until(...)
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/backoff.go:161
grafana-agent k8s.io/client-go/tools/cache.(*processorListener).run(0xc003039cb0)
grafana-agent     /go/pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/shared_informer.go:967 +0x6b
grafana-agent k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/wait.go:72 +0x5a
grafana-agent created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
grafana-agent     /go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/wait.go:70 +0x85
Stream closed EOF for monitoring/grafana-agent-system-2jhbm (grafana-agent)
```

**Comment by paul-bormans** [comment]
After some more debugging it seems targetPort needs to be defined (even though relabelings overwrite the __address__):
`spec:
  podMetricsEndpoints:
  - interval: 15s
    path: /stats/prometheus
    targetPort: 15020`

**Comment by captncraig** [comment]
I am fairly certain this is a bug that was [fixed](https://github.com/grafana/agent/pull/4886) in Grafana Agent v0.36.0. Can you update to a newer version?
