### ISSUE TITLE
remote_write endpoint panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by zhuoyuan-liu** [grafana/agent#6110]
### What's wrong?

The agent keeps getting the following error from v0.37.0 when pushing metrics to the remote_write endpoint.
`POST /agent/api/v1/metrics/instance/{instance}/write`

```
2024/01/11 04:54:59 http: panic serving 10.1.22.183:46236: duplicate metrics collector registration attempted
goroutine 2960 [running]:
net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x6ca1560?, 0xc0025de8e0?})
    /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
    /go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:150 +0x11e
panic({0x6ca1560?, 0xc0025de8e0?})
    /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x773a27f?, {0xc002ac7790?, 0x1, 0x3?})
    /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/registry.go:405 +0x78
github.com/prometheus/prometheus/storage/remote.NewWriteHandler({0x87a44c0?, 0xc002996500}, {0x87f3c30, 0xcf3af80}, {0x7f102c602958?, 0xc002782ea0})
    /go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20231016083943-46550094220d/storage/remote/write_handler.go:55 +0x1ac
github.com/grafana/agent/pkg/metrics.(*Agent).PushMetricsHandler(0xc0020e3800, {0x87fc2f0, 0xc0042f4480}, 0x87883a0?)
    /src/agent/pkg/metrics/http.go:154 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc0042fa200?, {0x87fc2f0?, 0xc0042f4480?}, 0x1?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000001a40, {0x87fc2f0, 0xc0042f4480}, 0xc0042fa100)
    /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
github.com/grafana/dskit/middleware.(*Instrument).Wrap.Instrument.Wrap.func1.2({0x87fc2f0?, 0xc0042f4480?})
    /go/pkg/mod/github.com/grafana/dskit@v0.0.0-20230829141140-06955c011ffd/middleware/instrument.go:74 +0x33
github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics(0xc002726510, {0x7f102c6b90e8, 0xc0042f25a0}, 0xc003adb7c0)
    /go/pkg/mod/github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:84 +0x1db
github.com/felixge/httpsnoop.CaptureMetricsFn({0x7f102c6b90e8, 0xc0042f25a0}, 0xc002662440?)
    /go/pkg/mod/github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:39 +0x4e
github.com/grafana/dskit/middleware.(*Instrument).Wrap.Instrument.Wrap.func1({0x7f102c6b90e8, 0xc0042f25a0}, 0xc0042fa100)
    /go/pkg/mod/github.com/grafana/dskit@v0.0.0-20230829141140-06955c011ffd/middleware/instrument.go:73 +0x306
net/http.HandlerFunc.ServeHTTP(0x87fbe10?, {0x7f102c6b90e8?, 0xc0042f25a0?}, 0xc0040fdef0?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/grafana/dskit/middleware.(*Log).Wrap.Log.Wrap.func1({0x87fbe10, 0xc0038a0780}, 0xc0042fa100)
    /go/pkg/mod/github.com/grafana/dskit@v0.0.0-20230829141140-06955c011ffd/middleware/logging.go:88 +0x277
net/http.HandlerFunc.ServeHTTP(0x0?, {0x87fbe10?, 0xc0038a0780?}, 0x480425?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5({0x87f3700?, 0xc0040f27e0}, 0xc0042fa000)
    /go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:154 +0x4f7
net/http.HandlerFunc.ServeHTTP(0x4132c5?, {0x87f3700?, 0xc0040f27e0?}, 0xc0040f2701?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0x87c64a0?}, {0x87f3700?, 0xc0040f27e0?}, 0x6?)
    /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0039f93b0, {0x8817970, 0xc002b820f0})
    /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 293
    /usr/local/go/src/net/http/server.go:3086 +0x5cb
```

### Steps to reproduce

Use any Grafana agent version above v0.37.0 with static mode and send metrics to the remote_write endpoint.

### Software version

v0.38.1

**Comment by tpaschalis** [comment]
Hey there @zhuoyuan-liu, thanks for the report.

Could you provide the configuration file that you're using as it might help pinpoint what's going on?

**Comment by zhuoyuan-liu** [comment]
@tpaschalis Thanks for the quick reply. 
There is no issue in the version before v0.37.

```yaml
server:
  log_level: info
  
metrics:
  wal_directory: /data/grafana-agent-wal
  wal_cleanup_age: "1h"
  global:
    remote_write:
      - url: http://mimir.mimir.svc:8080/api/v1/push
        queue_config:
          min_backoff: 1s
          max_backoff: 2m
    external_labels:
      env: dev
  configs:
    - name: remote-write
```

**Comment by tpaschalis** [comment]
Thanks @zhuoyuan-liu.

So you're sending logs to this 'receiver' Agent by using the `/agent/api/v1/metrics/instance/remote-write/write`endpoint (substituting `{instance}`) from another 'sender' Agent.

On which of the two agents does the panic appear? Are they both in static mode? Could you also share the config for the second Agent in case there's anything interesting at it?

**Comment by zhuoyuan-liu** [comment]
We send the metrics from our application to the 'receiver' Agent using the API, and the agent will forward to Mimir. 

The only change we did was upgrading the grafana agent version.

**Comment by tpaschalis** [comment]
Ok, the culprit is likely https://github.com/prometheus/prometheus/commit/2b7202c4ccf3ff8e61d4c509c6f6b4283ef1d9b5, which was first introduced in Prometheus v2.46; during the Agent v0.37 release we upgraded Prometheus from v2.45 to include this change.

**Comment by zhuoyuan-liu** [comment]
@tpaschalis Thanks, I just want to mention the same thing. I will update the code and get back to you.

**Comment by zhuoyuan-liu** [comment]
@tpaschalis It seems that I cannot fix the issue, could you please take another look :)

**Comment by tpaschalis** [comment]
@zhuoyuan-liu issue should be fixed in main and will be included in the next Agent v0.40 release.

In the meantime, you can either build off main, or use one of the images published in our [DockerHub repo](https://hub.docker.com/r/grafana/agent). Thanks for bringing this to our attention! 🙌
