### ISSUE TITLE
0.40.0-rc.1: panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#6510]
### What's wrong?

Starting Grafana Agent `docker.io/grafana/agent:v0.40.0-rc.0` with the config below results into a panic. The config works fine at `v0.37.3`

### Steps to reproduce

Starting Grafana Agent `docker.io/grafana/agent:v0.40.0-rc.0` with the config below.

i guess its an combination of `remote.http` and `loki.write`. Remove `remote.http` resolves the issue.

The http endpoint returns a JSON:

```json
{"resourceId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/agent-test-imds-mock", "name": "agent-test-imds-mock", "tagsList": [{"name": "cdt-operations-tier", "value": "mock"}]}
```

### System information

Linux

### Software version

0.40.0-rc.1

### Configuration

```text
remote.http "imds" {
    url            = coalesce(env("OPSSTACK_AGENT_IMDS_ENDPOINT"), "http://169.254.169.254") + "/metadata/instance/compute?api-version=2021-02-01"
    headers = {
        "Metadata" = "true",
    }
    poll_frequency = "86400s"
    poll_timeout   = "1s"
}


logging {
    level  = "warn"
    format = "json"
    write_to = [loki.write.remote.receiver]
}

loki.write "remote" {
    external_labels = {
        "vmName" = json_decode(nonsensitive(remote.http.imds.content))["name"],
        "os"     = constants.os,
        "id"     = to_lower(json_decode(nonsensitive(remote.http.imds.content))["resourceId"]),
    }

    endpoint {
        name      = "opsstack"
        url       = env("OPSSTACK_AGENT_REMOTE_URL") + "/loki/api/v1/push"
        headers   = {
            "Host" = coalesce(env("OPSSTACK_AGENT_REMOTE_HOSTNAME"), replace(env("OPSSTACK_AGENT_REMOTE_URL"), "https://", "")),
            "X-OpsStack-Resource-ID" = json_decode(nonsensitive(remote.http.imds.content))["resourceId"],
            "X-OpsStack-Resource-OS" = constants.os,
        }
        tenant_id = "agent"

        basic_auth {
            username = env("OPSSTACK_AGENT_REMOTE_USERNAME")
            password = env("OPSSTACK_AGENT_REMOTE_PASSWORD")
        }
    }
}

// Local Debugging

// prometheus.scrape "local" {
//   targets    = [/* ... */]
//   forward_to = [module.http.all.exports.prometheus.receiver]
// }
```

### Logs

```text
panic: duplicate metrics collector registration attempted

goroutine 180 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0x4002f974d0, {0x400300e740?, 0x1, 0xa?})
	/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/wrap.go:104 +0x158
github.com/grafana/agent/component/common/loki/client/internal.NewMarkerMetrics({0x8284290, 0x4002f974d0})
	/src/agent/component/common/loki/client/internal/metrics.go:22 +0x1c4
github.com/grafana/agent/component/common/loki/client.NewManager(0x0?, {0x8233420, 0x4002f7b540}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
	/src/agent/component/common/loki/client/manager.go:92 +0x84
github.com/grafana/agent/component/loki/write.(*Component).Update(0x4002904fc0, {0x6a5dc20?, 0x4002f7be50?})
	/src/agent/component/loki/write/write.go:198 +0x468
github.com/grafana/agent/pkg/flow/internal/controller.(*BuiltinComponentNode).evaluate(0x4002fa8000, 0x0?)
	/src/agent/pkg/flow/internal/controller/node_builtin_component.go:286 +0x220
github.com/grafana/agent/pkg/flow/internal/controller.(*BuiltinComponentNode).Evaluate(0x4002f7a6e0?, 0xfdcf91d68730?)
	/src/agent/pkg/flow/internal/controller/node_builtin_component.go:241 +0x20
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).concurrentEvalFn(0x4002ef8c00, {0xfdcf91d68730, 0x4002fa8000}, {0x82a83e8, 0x4002fb0420}, {0x8259860, 0x4002fb0360}, 0x40028e8330)
	/src/agent/pkg/flow/internal/controller/loader.go:747 +0x374
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).EvaluateDependants.func2()
	/src/agent/pkg/flow/internal/controller/loader.go:699 +0x3c
github.com/grafana/agent/pkg/flow/internal/worker.(*workQueue).emitNextTask.func1()
	/src/agent/pkg/flow/internal/worker/worker_pool.go:181 +0x6c
github.com/grafana/agent/pkg/flow/internal/worker.(*fixedWorkerPool).start.func1()
	/src/agent/pkg/flow/internal/worker/worker_pool.go:87 +0x68
created by github.com/grafana/agent/pkg/flow/internal/worker.(*fixedWorkerPool).start in goroutine 1
	/src/agent/pkg/flow/internal/worker/worker_pool.go:80 +0x2c
```

**Comment by jkroepke** [comment]
Thanks for the quick fix!
