### ISSUE TITLE
0.40.0: panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by emilylange** [grafana/agent#6548]
Coming from https://github.com/NixOS/nixpkgs/pull/292122, where our VM test fails with a similar looking panic from #6510 and #6511.

We start `grafana-agent` via `grafana-agent -config.expand-env -config.file <path to config file>` with the following config:

```yaml
integrations:
  agent:
    enabled: true
    scrape_integration: true
  node_exporter:
    enabled: true
metrics:
  global:
    scrape_interval: 5s
  wal_directory: ${STATE_DIRECTORY}
```

Resulting in the following panic.
Can provide full logs if needed.

```
panic: duplicate metrics collector registration attempted
goroutine 301 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc002f581b0, {0xc001ec8eb0?, 0x1, 0x3?})
        github.com/prometheus/client_golang@v1.18.0/prometheus/wrap.go:104 +0x145
github.com/prometheus/prometheus/storage/remote.NewWriteHandler({0x89c5200?, 0xc00333bd60}, {0x8a15f10, 0xc002f581b0}, {0x7f8335158a78?, 0xc00333d0a0})
        github.com/prometheus/prometheus@v1.99.0/storage/remote/write_handler.go:55 +0x1ac
github.com/grafana/agent/pkg/metrics/instance.(*Instance).initialize(0xc0033bc1c0, {0x8a3a170, 0xc00333be00}, {0x8a15ee0, 0xc001c59f38}, 0xc0002e2500)
        github.com/grafana/agent/pkg/metrics/instance/instance.go:412 +0x1fa
github.com/grafana/agent/pkg/metrics/instance.(*Instance).Run(0xc0033bc1c0, {0x8a3a170, 0xc00333be00})
        github.com/grafana/agent/pkg/metrics/instance/instance.go:309 +0x328
github.com/grafana/agent/pkg/metrics/instance.(*BasicManager).runProcess(0xc0031d4ac0, {0x8a3a170, 0xc00333be00}, {0xc003335a40, 0x20}, {0x8a58d10, 0xc0033bc1c0})
        github.com/grafana/agent/pkg/metrics/instance/manager.go:265 +0xa3
github.com/grafana/agent/pkg/metrics/instance.(*BasicManager).spawnProcess.func1()
        github.com/grafana/agent/pkg/metrics/instance/manager.go:235 +0x53
created by github.com/grafana/agent/pkg/metrics/instance.(*BasicManager).spawnProcess in goroutine 1
        github.com/grafana/agent/pkg/metrics/instance/manager.go:234 +0x345
```

Version info is different from the official release binaries, because we compile from source in nixpkgs.

```bash
$ grafana-agent --version
agent, version 0.40.0 (branch: v0.40.0, revision: v0.40.0)
  build user:       nix
  build date:       1980-01-01T00:00:00Z
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             builtinassets,nonetwork,nodocker,promtail_journal_enabled
```

Just to avoid confusion:
`ldflags` are set here: https://github.com/NixOS/nixpkgs/blob/bb6e397a6a0318140fb0ba36d7612f1c6704f879/pkgs/servers/monitoring/grafana-agent/default.nix#L34-L44
and build `tags` here: https://github.com/NixOS/nixpkgs/blob/bb6e397a6a0318140fb0ba36d7612f1c6704f879/pkgs/servers/monitoring/grafana-agent/default.nix#L48-L53

**Comment by emilylange** [comment]
Happens on https://github.com/grafana/agent/releases/tag/v0.40.1 as well

**Comment by 7840vz** [comment]
Having same issue.

**Comment by 1kUHuiswkvj7spRO** [comment]
Same issue here

**Comment by a-patos** [comment]
same for me
