### ISSUE TITLE
otelcol: panic when fanning out to invalid receiver block

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6746]
### What's wrong?

If I try to use an invalid block as an OpenTelemetry collector component, I'm getting a nice diagnostic message.

```
ts=2024-03-21T16:28:26.334552708Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=8fe54bb38a32efde35f3fd23e1c7866e duration=1.563579ms
Error: panic.river:23:2: unrecognized attribute name "badarg"

22 |     }
23 |     badarg = "badval"
   |     ^^^^^^^^^^^^^^^^^
24 | }

Error: panic.river:1:1: Failed to build component: building component: nil next Consumer

 1 |   otelcol.receiver.otlp "default" {
   |  _^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 2 | |     grpc { }
 3 | |
 4 | |     http { }
 5 | |
 6 | |     output {
 7 | |         // With a single 'bad' exporter, the error is properly seen as a diagnostic
 8 | |         metrics = [otelcol.exporter.otlphttp.b.input]
 9 | |         logs    = [otelcol.exporter.otlphttp.b.input]
10 | |         traces  = [otelcol.exporter.otlphttp.b.input]
11 | |
12 | |         // With multiple consumers, when either of them is 'bad', we result in a panic
13 | |         /* metrics = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input] */
14 | |         /* logs    = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input] */
15 | |         /* traces  = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input] */
16 | |     }
17 | | }
   | |_^
18 |

Error: could not perform the initial load successfully
```

If I try to fan out to both a valid _and_ an invalid recveiver, I get a panic instead.

### Steps to reproduce

Run the provided configuration with either of the output block alternatives and see the difference

### System information

Windows 11N

### Software version

main (514c541a0f4e0e097e9fda45934d7b19c03f1f46)

### Configuration

```text
otelcol.receiver.otlp "default" {
	grpc { }

	http { }

	output {
		// With a single 'bad' exporter, the error is properly seen as a diagnostic
		/* metrics = [otelcol.exporter.otlphttp.b.input] */
		/* logs    = [otelcol.exporter.otlphttp.b.input] */
		/* traces  = [otelcol.exporter.otlphttp.b.input] */

		// With multiple consumers, when any of them can't be evaluated (and results in a nil receiver) we get a panic
		metrics = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input]
		logs    = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input]
		traces  = [otelcol.exporter.otlphttp.b.input, otelcol.exporter.otlphttp.b.input]
	}
}

otelcol.exporter.otlphttp "b" {
	client {
		endpoint = "database:4318"
	}
	badarg = "badval"
}
```

### Logs

```text
./build/grafana-agent-flow run panic.river
ts=2024-03-21T16:29:37.566406787Z level=info "boringcrypto enabled"=false
ts=2024-03-21T16:29:37.566438938Z level=info msg="running usage stats reporter"
ts=2024-03-21T16:29:37.566443527Z level=info msg="starting complete graph evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900
ts=2024-03-21T16:29:37.566462503Z level=info msg="applying non-TLS config to HTTP server" service=http
ts=2024-03-21T16:29:37.566479865Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=http duration=7.925µs
ts=2024-03-21T16:29:37.566499132Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=cluster duration=270ns
ts=2024-03-21T16:29:37.56651918Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=ui duration=291ns
ts=2024-03-21T16:29:37.566542514Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=logging duration=136.719µs
ts=2024-03-21T16:29:37.566575036Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=labelstore duration=3.677µs
ts=2024-03-21T16:29:37.566597658Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=otel duration=782ns
ts=2024-03-21T16:29:37.566657682Z level=error msg="failed to evaluate config" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node=otelcol.exporter.otlphttp.b err="decoding River: panic.river:23:2: unrecognized attribute name \"badarg\""
ts=2024-03-21T16:29:37.56668313Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=otelcol.exporter.otlphttp.b duration=64.011µs
ts=2024-03-21T16:29:37.566855306Z level=info msg="finished node evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 node_id=otelcol.receiver.otlp.default duration=149.844µs
ts=2024-03-21T16:29:37.566879622Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=7642391647b1c380552a9629ddc86900 duration=533.4µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x58b7b10]

goroutine 1 [running]:
github.com/grafana/agent/internal/component/otelcol/internal/fanoutconsumer.Traces({0xc002c4e8c0, 0x2, 0x2})
        /home/tpaschalis/GitRepos/agent/internal/component/otelcol/internal/fanoutconsumer/traces.go:34 +0x1d0
github.com/grafana/agent/internal/component/otelcol/receiver.(*Receiver).Update(0xc002918f20, {0x755b2c0?, 0xc002c4e940})
        /home/tpaschalis/GitRepos/agent/internal/component/otelcol/receiver/receiver.go:156 +0x6d2
github.com/grafana/agent/internal/component/otelcol/receiver.New({{0x7f61a4263738, 0xc002c2df50}, {0xc000117de0, 0x1d}, {0x8a8cca0, 0xc0020e4e60}, {0xc0020c92c0, 0x28}, 0xc0020d7500, {0x8ade420, ...}, ...}, ...)
        /home/tpaschalis/GitRepos/agent/internal/component/otelcol/receiver/receiver.go:93 +0x272
github.com/grafana/agent/internal/component/otelcol/receiver/otlp.init.0.func1({{0x7f61a4263738, 0xc002c2df50}, {0xc000117de0, 0x1d}, {0x8a8cca0, 0xc0020e4e60}, {0xc0020c92c0, 0x28}, 0xc0020d7500, {0x8ade420, ...}, ...}, ...)
        /home/tpaschalis/GitRepos/agent/internal/component/otelcol/receiver/otlp/otlp.go:26 +0xf2
github.com/grafana/agent/internal/flow/internal/controller.(*BuiltinComponentNode).evaluate(0xc0020ea6c8, 0xc0020d7b40)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/node_builtin_component.go:270 +0x483
github.com/grafana/agent/internal/flow/internal/controller.(*BuiltinComponentNode).Evaluate(0xc0020ea6c8, 0x6cdeb20?)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/node_builtin_component.go:243 +0x1c
github.com/grafana/agent/internal/flow/internal/controller.(*Loader).evaluate(0xc001e7aea0, {0x8a8cca0, 0xc0020e4fa0}, {0x8b04368, 0xc0020ea6c8})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/loader.go:828 +0x49
github.com/grafana/agent/internal/flow/internal/controller.(*Loader).Apply.func2({0x7f61a4263758, 0xc0020ea6c8})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/loader.go:199 +0x1085
github.com/grafana/agent/internal/flow/internal/dag.WalkTopological(0xc002c2be80, {0xc0020af000, 0x7, 0xcf29ab0?}, 0xc002339358)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/dag/walk.go:83 +0x222
github.com/grafana/agent/internal/flow/internal/controller.(*Loader).Apply(0xc001e7aea0, {0x0, {0xc0020d73f0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/loader.go:182 +0xb2d
github.com/grafana/agent/internal/flow.(*Flow).loadSource(0xc002c041e0, 0xc002068b60, 0x0, 0x0)
        /home/tpaschalis/GitRepos/agent/internal/flow/flow.go:310 +0x1b8
github.com/grafana/agent/internal/flow.(*Flow).LoadSource(...)
        /home/tpaschalis/GitRepos/agent/internal/flow/flow.go:294
github.com/grafana/agent/internal/flowmode.(*flowRun).Run.func4()
        /home/tpaschalis/GitRepos/agent/internal/flowmode/cmd_run.go:303 +0x28a
github.com/grafana/agent/internal/flowmode.(*flowRun).Run(0xc002c04000, {0x7ffdabb45360, 0xb})
        /home/tpaschalis/GitRepos/agent/internal/flowmode/cmd_run.go:336 +0xf67
github.com/grafana/agent/internal/flowmode.runCommand.func1(0xc0000fd300?, {0xc0020d6650?, 0x4?, 0x799ab47?})
        /home/tpaschalis/GitRepos/agent/internal/flowmode/cmd_run.go:98 +0x2b
github.com/spf13/cobra.(*Command).execute(0xc002c00608, {0xc0020d6620, 0x1, 0x1})
        /home/tpaschalis/GitRepos/agent/vendor/github.com/spf13/cobra/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc001f01b08)
        /home/tpaschalis/GitRepos/agent/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/tpaschalis/GitRepos/agent/vendor/github.com/spf13/cobra/command.go:992
github.com/grafana/agent/internal/flowmode.Run()
        /home/tpaschalis/GitRepos/agent/internal/flowmode/flowmode.go:33 +0x2f8
main.main()
        /home/tpaschalis/GitRepos/agent/cmd/grafana-agent-flow/main.go:31 +0xf
```

**Comment by tpaschalis** [comment]
My gut feeling is that some nilness check is satisfied when there's a single consumer, but when we're fanning out to multiple entries, that's not the case.

So, in case there's only 1 receiver, we pass it along as-is, triggering the correct nilness check: https://github.com/grafana/agent/blob/514c541a0f4e0e097e9fda45934d7b19c03f1f46/internal/component/otelcol/internal/fanoutconsumer/traces.go#L22-L24

But if there's 2 or more, we actually pass in a tracesFanout instance, which will never be nil, but might have nil elements in it.
https://github.com/grafana/agent/blob/514c541a0f4e0e097e9fda45934d7b19c03f1f46/internal/component/otelcol/internal/fanoutconsumer/traces.go#L49-L52

Note that https://github.com/open-telemetry/opentelemetry-collector/commit/08a692279c1e21bc8dc105b120e633f677267122 is going to be included along @ptodev's work on #6725 to update the OTel collector version which changes the handling of nil consumers so the fix will have to be validated after that upgrade lands as well.
