### ISSUE TITLE
flaky panic on CustomComponentRegistry.getDeclare

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6795]
### What's wrong?

I'm running the following configuration as part of #6260 to investigate nested modules. 

On the current main 5e037eb I'm getting a panic on startup every now and then. It's not always reproducible

### Steps to reproduce

Create four files with the contents presented below (entrypoint.river, a.river, b.river, c.river) and run the first one.

### System information

Windows 11N

### Software version

main (5e037eb)

### Configuration

```text
--- entrypoint.river ---

import.file "a_namespace" {
	filename = "a.river"
}

a_namespace.a "default" {
	a_argument = 47
}


--- a.river --- 
declare "a" {
	import.file "b_namespace" {
		filename = "b.river"
	}

	argument "a_argument" {
		comment = "Where to send collected metrics."
	}

	prometheus.exporter.self "default" { }

	b_namespace.b "default" {
		b_argument = 147
	}

	export "a_export" {
		value = argument.a_argument.value + b_namespace.b.default.b_export + 1
	}
}

--- b.river ---
declare "b" {
	import.file "c_namespace" {
		filename = "c.river"
	}

	argument "b_argument" {
		optional = false
	}

	prometheus.exporter.self "default" { }

	c_namespace.c "default" {
		c_argument = 101
	}

	export "b_export" {
		value = argument.b_argument.value + c_namespace.c.default.c_export + 1
	}
}

--- c.river ---
declare "c" {
	argument "c_argument" {
		optional = false
	}

	prometheus.exporter.self "default" { }

	prometheus.scrape "default" {
		targets    = prometheus.exporter.self.default.targets
		forward_to = []
	}

	export "c_export" {
		value = argument.c_argument.value + 1
	}
}
```

### Logs

```text
./build/grafana-agent-flow-main run entrypoint.river
ts=2024-03-29T12:33:32.758189475Z level=info "boringcrypto enabled"=false
ts=2024-03-29T12:33:32.75822405Z level=info msg="running usage stats reporter"
ts=2024-03-29T12:33:32.758228599Z level=info msg="starting complete graph evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13
ts=2024-03-29T12:33:32.758247424Z level=info msg="applying non-TLS config to HTTP server" service=http
ts=2024-03-29T12:33:32.758253235Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=http duration=7.464µs
ts=2024-03-29T12:33:32.758269766Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=ui duration=220ns
ts=2024-03-29T12:33:32.758288963Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=cluster duration=291ns
ts=2024-03-29T12:33:32.758307788Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=remotecfg duration=16.782µs
ts=2024-03-29T12:33:32.758326764Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=labelstore duration=1.293µs
ts=2024-03-29T12:33:32.758334138Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=otel duration=170ns
ts=2024-03-29T12:33:32.758337555Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=tracing duration=1.833µs
ts=2024-03-29T12:33:32.758341853Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=logging duration=153.591µs
ts=2024-03-29T12:33:32.75843031Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=import.file.a_namespace duration=71.125µs
ts=2024-03-29T12:33:32.758531842Z level=info msg="starting complete graph evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85
ts=2024-03-29T12:33:32.758865583Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 node_id=prometheus.exporter.self.default duration=16.07µs
ts=2024-03-29T12:33:32.758899387Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 node_id=argument.a_argument duration=10.409µs
ts=2024-03-29T12:33:32.758971924Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 node_id=import.file.b_namespace duration=51.106µs
ts=2024-03-29T12:33:32.759039212Z level=info msg="starting complete graph evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01
ts=2024-03-29T12:33:32.759077644Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 node_id=argument.b_argument duration=3.276µs
ts=2024-03-29T12:33:32.759146134Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 node_id=import.file.c_namespace duration=45.817µs
ts=2024-03-29T12:33:32.759206177Z level=info msg="starting complete graph evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1
ts=2024-03-29T12:33:32.759233699Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1 node_id=argument.c_argument duration=3.146µs
ts=2024-03-29T12:33:32.759269387Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1 node_id=export.c_export duration=10.78µs
ts=2024-03-29T12:33:32.759299594Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1 node_id=prometheus.exporter.self.default duration=8.536µs
ts=2024-03-29T12:33:32.759598259Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1 node_id=prometheus.scrape.default duration=276.863µs
ts=2024-03-29T12:33:32.759622505Z level=info msg="finished complete graph evaluation" controller_id=a_namespace.a.default/b_namespace.b.default/c_namespace.c.default trace_id=983256f6bef7838a89fd1fa1d995edf1 duration=433.781µs
ts=2024-03-29T12:33:32.759647923Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 node_id=c_namespace.c.default duration=479.387µs
ts=2024-03-29T12:33:32.759668712Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 node_id=export.b_export duration=10.069µs
ts=2024-03-29T12:33:32.759696735Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 node_id=prometheus.exporter.self.default duration=9.508µs
ts=2024-03-29T12:33:32.759724437Z level=info msg="finished complete graph evaluation" controller_id=a_namespace.a.default/b_namespace.b.default trace_id=dad742f10e6a5d9de993038912bd3a01 duration=707.337µs
ts=2024-03-29T12:33:32.759746199Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 node_id=b_namespace.b.default duration=751.752µs
ts=2024-03-29T12:33:32.759775664Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 node_id=export.a_export duration=8.065µs
ts=2024-03-29T12:33:32.759797365Z level=info msg="finished complete graph evaluation" controller_id=a_namespace.a.default trace_id=1c2bb8a8a45665e73c51aff7392a6f85 duration=1.294898ms
ts=2024-03-29T12:33:32.759818405Z level=info msg="finished node evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 node_id=a_namespace.a.default duration=1.364941ms
ts=2024-03-29T12:33:32.759838543Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=a0867941e227359e93275920d6647d13 duration=1.732406ms
ts=2024-03-29T12:33:32.759998907Z level=info msg="scheduling loaded components and services"
ts=2024-03-29T12:33:32.760068118Z level=info msg="scheduling loaded components and services"
ts=2024-03-29T12:33:32.760068218Z level=info msg="starting cluster node" peers="" advertise_addr=127.0.0.1:12345
ts=2024-03-29T12:33:32.760141671Z level=info msg="starting complete graph evaluation" controller_id=a_namespace.a.default trace_id=e2ea4ce7ddb67a5d3e4d6e208232a056
ts=2024-03-29T12:33:32.760191956Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default trace_id=e2ea4ce7ddb67a5d3e4d6e208232a056 node_id=prometheus.exporter.self.default duration=9.438µs
ts=2024-03-29T12:33:32.760202702Z level=info msg="peers changed" new_peers=ookami
ts=2024-03-29T12:33:32.760232478Z level=info msg="finished node evaluation" controller_id=a_namespace.a.default node_id=b_namespace.b.default duration=57.018µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18e7afc]

goroutine 214 [running]:
github.com/grafana/agent/internal/flow/internal/controller.(*CustomComponentRegistry).getDeclare(0xc002800610?, {0xc002b689cc?, 0x62fd480?})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/custom_component_registry.go:32 +0x3c
github.com/grafana/agent/internal/flow/internal/controller.findImportedDeclare(0xc002f40d80, {0xc002b689c0, 0xb}, {0xc002b689cc, 0x1})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/component_node_manager.go:93 +0x48
github.com/grafana/agent/internal/flow/internal/controller.(*ComponentNodeManager).getCustomComponentConfig(0xc002b66be0, {0xc002b689c0, 0xb}, {0xc002b689cc, 0x1})
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/component_node_manager.go:58 +0x117
github.com/grafana/agent/internal/flow/internal/controller.(*CustomComponentNode).evaluate(0xc002b7a4e0, 0xc002d86050)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/node_custom_component.go:198 +0x285
github.com/grafana/agent/internal/flow/internal/controller.(*CustomComponentNode).Evaluate(0xc002b7a4e0, 0x7768fc0?)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/node_custom_component.go:166 +0x1c
github.com/grafana/agent/internal/flow/internal/controller.(*Loader).concurrentEvalFn(0xc002b7a340, {0x8c00a40, 0xc002b7a4e0}, {0x8c75c30, 0xc002e00450}, {0x8c22bf8, 0xc002e00300}, 0xc002ea4780)
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/loader.go:790 +0x61e
github.com/grafana/agent/internal/flow/internal/controller.(*Loader).EvaluateDependants.func2()
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/controller/loader.go:742 +0x33
github.com/grafana/agent/internal/flow/internal/worker.(*workQueue).emitNextTask.func1()
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/worker/worker_pool.go:181 +0x6c
github.com/grafana/agent/internal/flow/internal/worker.(*fixedWorkerPool).start.func1()
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/worker/worker_pool.go:87 +0x6d
created by github.com/grafana/agent/internal/flow/internal/worker.(*fixedWorkerPool).start in goroutine 1
        /home/tpaschalis/GitRepos/agent/internal/flow/internal/worker/worker_pool.go:80 +0x25
```

**Comment by tpaschalis** [comment]
From a quick investigation I think the issue is here; https://github.com/grafana/agent/blob/88780b8ee7ee74234ca5d86535a3ab1d553c098e/internal/flow/internal/controller/component_node_manager.go#L93

This line calls getDeclare on an import that has been registered as nil but hasn't been updated with its content yet. Go will allow you to call methods against a nil struct, so it panics on the next line it tries to access one of its fields.

**Comment by tpaschalis** [comment]
Trying to understand what's happening, the issue is around:

https://github.com/grafana/agent/blob/main/internal/flow/internal/controller/component_node_manager.go#L93

The contents are updated but for some reason the namespace is re-registered as nil, leading to the panic.
